/* 3615 Bleus V1.1.61.12 — Liste du sélectionneur avancée */
(()=>{
  'use strict';
  const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const norm=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
  const db=()=>window.BLEUS3000_SUPABASE||null, account=()=>window.C3K_ACCOUNT_STATE||{};
  const LOCAL_KEY='bleus3000.selection-lists.v1';
  const GROUPS=[
    {key:'goalkeeper',label:'Gardien',singular:'Gardien',count:3},
    {key:'defense',label:'Défense',singular:'Défenseur',count:8},
    {key:'midfield',label:'Milieu',singular:'Milieu',count:7},
    {key:'attack',label:'Attaquant',singular:'Attaquant',count:8}
  ];
  let state={counts:Object.fromEntries(GROUPS.map(g=>[g.key,g.count])),slots:{},title:'Ma liste France',competitionId:'',competitionName:'',savedId:null,saved:[],competitions:[],busy:false};

  function players(){return window.BLEUS3000_PLAYER_REGISTRY_ALL||window.BLEUS3000_PLAYER_REGISTRY||[];}
  function positionGroup(p){
    const v=norm(p?.position||p?.positions?.[0]||'');
    if(/gardien|goalkeeper|\bgb\b/.test(v))return 'goalkeeper';
    if(/defenseur|defense|lateral|arriere|piston|stoppeur|libero|back/.test(v))return 'defense';
    if(/milieu|demi|inter|midfield/.test(v))return 'midfield';
    if(/attaquant|ailier|avant centre|avant-centre|faux neuf|neuf|striker|forward|winger/.test(v))return 'attack';
    return '';
  }
  function photoUrl(p){const raw=String(p?.photo_path||'').trim();if(!raw)return '';if(/^https?:\/\//i.test(raw)||/^data:/i.test(raw)||raw.startsWith('/'))return raw;try{return db()?.storage?.from('player-photos')?.getPublicUrl(raw)?.data?.publicUrl||'';}catch{return '';}}
  function initials(name){return String(name||'?').trim().split(/\s+/).filter(Boolean).map(x=>x[0]).join('').slice(0,2).toUpperCase()||'?';}
  function iconHtml(p){const u=photoUrl(p);return u?`<span class="selection-list-player-icon"><img src="${esc(u)}" alt="" loading="lazy" onerror="this.parentNode.innerHTML='${esc(initials(p.name||p.display_name))}'"></span>`:`<span class="selection-list-player-icon is-initials">${esc(initials(p.name||p.display_name))}</span>`;}
  function slotKey(group,index){return `${group}:${index}`;}
  function selectedIds(){return new Set(Object.values(state.slots).map(x=>String(x?.id||'')).filter(Boolean));}
  function matchesGroup(p,group){const pg=positionGroup(p);if(!pg)return true;if(pg===group)return true;return (p.positions||[]).some(pos=>positionGroup({position:pos})===group);}
  function searchPlayers(q,group){const n=norm(q),chosen=selectedIds();if(n.length<2)return [];return players().filter(p=>!chosen.has(String(p.id))&&matchesGroup(p,group)&&norm([p.name,p.display_name,...(p.name_variants||[])].join(' ')).includes(n)).slice(0,8);}

  async function loadCompetitions(){const c=db();if(!c){state.competitions=[];return;}const {data,error}=await c.from('competition_families').select('id,slug,name,competition_type,sort_order').order('sort_order').order('name');if(error){console.warn('Liste · compétitions',error);state.competitions=[];}else state.competitions=data||[];}
  function localRows(){try{return JSON.parse(localStorage.getItem(LOCAL_KEY)||'[]')||[];}catch{return [];}}
  function setLocalRows(rows){localStorage.setItem(LOCAL_KEY,JSON.stringify(rows.slice(0,50)));}
  async function loadSaved(){const c=db(),a=account();if(c&&a.session?.user?.id){const {data,error}=await c.from('user_compositions').select('*').eq('user_id',a.session.user.id).eq('composition_type','selection_list').order('updated_at',{ascending:false});if(error)console.warn('Listes sauvegardées',error);state.saved=data||[];}else state.saved=localRows();return state.saved;}

  function ensureModal(){
    const m=$('#listToolModal');if(!m)return null;m.querySelector('.modal-dialog')?.classList.add('selection-list-dialog');return m;
  }
  function competitionOptions(){return `<option value="">Aucune compétition associée</option>`+state.competitions.map(c=>`<option value="${esc(c.id)}" ${String(state.competitionId)===String(c.id)?'selected':''}>${esc(c.name)}</option>`).join('');}
  function builderGroup(g){const n=state.counts[g.key]||0;return `<section class="selection-list-group" data-list-group="${g.key}"><header><div><strong>${esc(g.label)}</strong><small>${n} joueur${n>1?'s':''}</small></div><div class="selection-list-count-controls"><button type="button" data-list-count="${g.key}" data-delta="-1" ${n<=0?'disabled':''}>−</button><span>${n}</span><button type="button" data-list-count="${g.key}" data-delta="1">＋</button></div></header><div class="selection-list-slots">${Array.from({length:n},(_,i)=>slotHtml(g,i)).join('')}</div></section>`;}
  function slotHtml(g,i){const key=slotKey(g.key,i),p=state.slots[key]||null;return `<div class="selection-list-slot" data-list-slot="${key}" data-group="${g.key}"><div data-list-icon>${p?iconHtml(p):'<span class="selection-list-player-icon is-empty">＋</span>'}</div><div class="selection-list-search"><input type="search" data-list-player-search autocomplete="off" placeholder="Rechercher un nom…" value="${esc(p?.name||p?.display_name||'')}"><div class="selection-list-suggestions" data-list-suggestions hidden></div></div>${p?`<button class="selection-list-remove" data-list-remove type="button" title="Retirer">×</button>`:''}</div>`;}
  function previewHtml(){return `<section class="selection-list-preview" id="selectionListPreview"><header class="selection-list-preview-head"><img src="3615-bleus-logo.png" alt="3615 Bleus"><div><span>3615 BLEUS · LISTE DU SÉLECTIONNEUR</span><strong id="selectionListPreviewTitle">${esc(state.title||'Ma liste France')}</strong><small id="selectionListPreviewCompetition">${esc(state.competitionName||'Liste libre')}</small></div><em>${totalCount()} joueur${totalCount()>1?'s':''}</em></header><div class="selection-list-preview-groups">${GROUPS.map(g=>previewGroup(g)).join('')}</div></section>`;}
  function previewGroup(g){const arr=Array.from({length:state.counts[g.key]||0},(_,i)=>state.slots[slotKey(g.key,i)]).filter(Boolean);return `<section><h4>${esc(g.label)}</h4><div>${arr.length?arr.map(p=>`<article>${iconHtml(p)}<span>${esc(p.name||p.display_name)}</span></article>`).join(''):'<p>Aucun joueur sélectionné</p>'}</div></section>`;}
  function totalCount(){return GROUPS.reduce((s,g)=>s+Number(state.counts[g.key]||0),0);}
  function selectedCount(){return Object.values(state.slots).filter(Boolean).length;}
  function render(){
    const m=ensureModal();if(!m)return;const dialog=$('.modal-dialog',m),head=$('.modal-head',m),body=$('.modal-body',m);
    head.innerHTML=`<div><h2>Liste du sélectionneur</h2><p>Liste personnalisable · recherche nominative · groupes de postes · export graphique</p></div><button class="modal-close" data-list-close type="button">×</button>`;
    body.innerHTML=`<div class="selection-list-controls"><label>Nom de la liste<input id="listTitleInput" value="${esc(state.title)}" maxlength="80"></label><label>Compétition<select id="selectionListCompetition">${competitionOptions()}</select></label><div class="selection-list-total"><div class="selection-list-total-controls"><button type="button" data-list-total-delta="-1">−</button><strong>${selectedCount()} / ${totalCount()}</strong><button type="button" data-list-total-delta="1">＋</button></div><span>joueurs renseignés / places</span></div><button class="secondary-btn" id="selectionListLibrary" type="button">💾 Mes listes (${state.saved.length})</button></div><div class="selection-list-workspace"><div class="selection-list-builder" id="listBuilderGrid">${GROUPS.map(builderGroup).join('')}</div>${previewHtml()}</div><div id="selectionListStatus" class="team-tool-status" hidden></div><div class="tool-actions selection-list-actions"><button class="primary-btn" id="saveListTool" type="button">💾 Enregistrer</button><button class="secondary-btn" id="exportListPng" type="button">⬇ PNG</button><button class="secondary-btn" id="exportListJpg" type="button">⬇ JPG</button></div>`;
    bindRendered();
  }
  function bindRendered(){
    const m=$('#listToolModal');$('[data-list-close]',m)?.addEventListener('click',close);
    $('#listTitleInput',m)?.addEventListener('input',e=>{state.title=e.target.value;updatePreview();});
    $('#selectionListCompetition',m)?.addEventListener('change',e=>{state.competitionId=e.target.value;state.competitionName=state.competitions.find(x=>String(x.id)===String(e.target.value))?.name||'';updatePreview();});
    $$('[data-list-count]',m).forEach(b=>b.addEventListener('click',()=>changeCount(b.dataset.listCount,Number(b.dataset.delta))));$$('[data-list-total-delta]',m).forEach(b=>b.addEventListener('click',()=>changeTotal(Number(b.dataset.listTotalDelta))));
    m.oninput=onSearch;m.onpointerdown=onSuggestion;m.onclick=e=>{onRemove(e);};
    $('#saveListTool',m)?.addEventListener('click',save);$('#exportListPng',m)?.addEventListener('click',()=>exportImage('png'));$('#exportListJpg',m)?.addEventListener('click',()=>exportImage('jpg'));$('#selectionListLibrary',m)?.addEventListener('click',openLibrary);
  }
  function changeCount(group,delta){const current=state.counts[group]||0,next=Math.max(0,Math.min(20,current+delta));if(next<current){for(let i=next;i<current;i++)delete state.slots[slotKey(group,i)];}state.counts[group]=next;render();}
  function changeTotal(delta){if(!delta)return;const defaults=Object.fromEntries(GROUPS.map(g=>[g.key,g.count]));if(delta>0){const g=[...GROUPS].sort((a,b)=>((state.counts[a.key]||0)/defaults[a.key])-((state.counts[b.key]||0)/defaults[b.key]))[0];state.counts[g.key]=Math.min(20,(state.counts[g.key]||0)+1);}else{const candidates=GROUPS.filter(g=>(state.counts[g.key]||0)>0).sort((a,b)=>((state.counts[b.key]||0)/defaults[b.key])-((state.counts[a.key]||0)/defaults[a.key]));const g=candidates.find(x=>!state.slots[slotKey(x.key,(state.counts[x.key]||1)-1)])||candidates[0];if(g){const old=state.counts[g.key]||0,newCount=Math.max(0,old-1);delete state.slots[slotKey(g.key,newCount)];state.counts[g.key]=newCount;}}render();}
  function onSearch(e){const input=e.target.closest?.('[data-list-player-search]');if(!input)return;const slot=input.closest('[data-list-slot]'),box=$('[data-list-suggestions]',slot),key=slot.dataset.listSlot;if(state.slots[key]&&norm(input.value)!==norm(state.slots[key].name||state.slots[key].display_name)){delete state.slots[key];$('[data-list-icon]',slot).innerHTML='<span class="selection-list-player-icon is-empty">＋</span>';$('.selection-list-remove',slot)?.remove();updatePreview();}const hits=searchPlayers(input.value,slot.dataset.group);if(!hits.length){box.hidden=true;box.innerHTML='';return;}box.innerHTML=hits.map(p=>`<button type="button" data-list-player="${esc(p.id)}"><span>${iconHtml(p)}</span><span><strong>${esc(p.name||p.display_name)}</strong><small>${esc((p.positions||[]).join(' · ')||p.position||'Joueur')}</small></span></button>`).join('');box.hidden=false;}
  function onSuggestion(e){const b=e.target.closest?.('[data-list-player]');if(!b)return;e.preventDefault();const slot=b.closest('[data-list-slot]'),p=players().find(x=>String(x.id)===String(b.dataset.listPlayer));if(!slot||!p)return;state.slots[slot.dataset.listSlot]=p;render();}
  function onRemove(e){const b=e.target.closest?.('[data-list-remove]');if(!b)return;const slot=b.closest('[data-list-slot]');if(slot){delete state.slots[slot.dataset.listSlot];render();}}
  function updatePreview(){const p=$('#selectionListPreview');if(!p)return;$('#selectionListPreviewTitle').textContent=state.title||'Ma liste France';$('#selectionListPreviewCompetition').textContent=state.competitionName||'Liste libre';p.querySelector('em').textContent=`${totalCount()} joueur${totalCount()>1?'s':''}`;p.querySelector('.selection-list-preview-groups').innerHTML=GROUPS.map(previewGroup).join('');const counter=$('.selection-list-total strong');if(counter)counter.textContent=`${selectedCount()} / ${totalCount()}`;}
  function payload(){return {competition_id:state.competitionId||null,competition_name:state.competitionName||null,counts:{...state.counts},players:GROUPS.flatMap(g=>Array.from({length:state.counts[g.key]||0},(_,i)=>{const p=state.slots[slotKey(g.key,i)];return p?{slot_index:i,group:g.key,group_label:g.label,player_id:p.id,name:p.name||p.display_name,photo_path:p.photo_path||null}:null;}).filter(Boolean))};}
  function status(msg,type='ok'){const e=$('#selectionListStatus');if(!e)return;e.hidden=false;e.className=`team-tool-status is-${type}`;e.textContent=msg;}
  async function save(){if(state.busy)return;state.busy=true;status('Enregistrement…');try{const title=String(state.title||'Ma liste France').trim()||'Ma liste France',row={composition_type:'selection_list',title,formation:null,payload:payload(),updated_at:new Date().toISOString()},c=db(),a=account();if(c&&a.session?.user?.id){row.user_id=a.session.user.id;let res;if(state.savedId)res=await c.from('user_compositions').update(row).eq('id',state.savedId).eq('user_id',a.session.user.id).select().single();else res=await c.from('user_compositions').insert(row).select().single();if(res.error)throw res.error;state.savedId=res.data.id;}else{let rows=localRows(),now=new Date().toISOString();if(state.savedId){const i=rows.findIndex(x=>String(x.id)===String(state.savedId));if(i>=0)rows[i]={...rows[i],...row,updated_at:now};}else{state.savedId=`local-${crypto.randomUUID?.()||Date.now()}`;rows.unshift({id:state.savedId,...row,created_at:now,updated_at:now});}setLocalRows(rows);}await loadSaved();status('Liste enregistrée dans ton profil.','ok');render();}catch(err){console.error(err);status(err.message||String(err),'error');}finally{state.busy=false;}}
  async function openLibrary(){await loadSaved();let modal=$('#selectionListLibraryModal');if(!modal){modal=document.createElement('div');modal.className='modal-backdrop';modal.id='selectionListLibraryModal';document.body.appendChild(modal);}modal.innerHTML=`<section class="modal-dialog team-library-dialog"><header class="modal-head"><div><h2>Mes listes</h2><p>Listes du sélectionneur enregistrées</p></div><button class="modal-close" data-list-library-close type="button">×</button></header><div class="modal-body"><div class="team-library-list">${state.saved.length?state.saved.map(r=>`<article class="team-saved-card"><div><strong>${esc(r.title)}</strong><small>${esc(r.payload?.competition_name||'Liste libre')} · ${(r.payload?.players||[]).length} joueurs</small></div><div><button class="secondary-btn" data-load-list="${esc(r.id)}">Charger</button><button class="team-saved-delete" data-delete-list="${esc(r.id)}">×</button></div></article>`).join(''):'<div class="team-library-empty">Aucune liste enregistrée.</div>'}</div></div></section>`;modal.hidden=false;modal.querySelector('[data-list-library-close]').onclick=()=>modal.hidden=true;modal.querySelectorAll('[data-load-list]').forEach(b=>b.onclick=()=>{const row=state.saved.find(x=>String(x.id)===String(b.dataset.loadList));modal.hidden=true;applySaved(row);});modal.querySelectorAll('[data-delete-list]').forEach(b=>b.onclick=async()=>{await deleteSaved(b.dataset.deleteList);modal.hidden=true;openLibrary();});}
  async function deleteSaved(id){const c=db(),a=account();if(c&&a.session?.user?.id){const {error}=await c.from('user_compositions').delete().eq('id',id).eq('user_id',a.session.user.id);if(error)throw error;}else setLocalRows(localRows().filter(x=>String(x.id)!==String(id)));if(String(state.savedId)===String(id))state.savedId=null;await loadSaved();}
  function applySaved(row){if(!row)return;const p=row.payload||{};state.savedId=row.id;state.title=row.title||'Ma liste France';state.competitionId=p.competition_id||'';state.competitionName=p.competition_name||'';state.counts={...Object.fromEntries(GROUPS.map(g=>[g.key,g.count])),...(p.counts||{})};state.slots={};for(const item of (p.players||[])){const pl=players().find(x=>String(x.id)===String(item.player_id))||{id:item.player_id,name:item.name,display_name:item.name,photo_path:item.photo_path};state.slots[slotKey(item.group,Number(item.slot_index||0))]=pl;}render();}
  function close(){const m=$('#listToolModal');if(m)m.hidden=true;document.body.style.overflow='';}
  async function safeImage(src){if(!src)return null;try{const u=new URL(src,document.baseURI).href,res=await fetch(u,{mode:'cors',cache:'force-cache'});if(!res.ok)return null;const blob=await res.blob(),obj=URL.createObjectURL(blob);const im=await new Promise((ok,no)=>{const x=new Image();x.onload=()=>ok(x);x.onerror=no;x.src=obj;});setTimeout(()=>URL.revokeObjectURL(obj),3000);return im;}catch{return null;}}
  async function exportImage(format='png'){status(`Préparation du ${format.toUpperCase()}…`);try{const W=1200,H=Math.max(900,340+totalCount()*42),canvas=document.createElement('canvas');canvas.width=W;canvas.height=H;const c=canvas.getContext('2d');c.fillStyle='#071426';c.fillRect(0,0,W,H);c.fillStyle='#f7faff';c.roundRect(40,40,W-80,H-80,32);c.fill();const logo=await safeImage('3615-bleus-logo.png');if(logo)c.drawImage(logo,82,75,185,100);c.fillStyle='#0c2f61';c.font='800 22px Poppins, Arial';c.fillText('3615 BLEUS · LISTE DU SÉLECTIONNEUR',305,100);c.font='900 44px Poppins, Arial';c.fillText(state.title||'Ma liste France',305,153);c.fillStyle='#68809d';c.font='700 20px Poppins, Arial';c.fillText(state.competitionName||'Liste libre',305,190);let y=260;for(const g of GROUPS){c.fillStyle='#123b8f';c.font='900 26px Poppins, Arial';c.fillText(g.label,y?82:82,y);y+=34;const arr=Array.from({length:state.counts[g.key]||0},(_,i)=>state.slots[slotKey(g.key,i)]).filter(Boolean);if(!arr.length){c.fillStyle='#8292a8';c.font='500 18px Poppins, Arial';c.fillText('Aucun joueur sélectionné',100,y);y+=38;continue;}for(const p of arr){c.fillStyle='#eef4ff';c.beginPath();c.arc(105,y-7,18,0,Math.PI*2);c.fill();c.fillStyle='#123b8f';c.textAlign='center';c.font='800 11px Arial';c.fillText(initials(p.name||p.display_name),105,y-3);c.textAlign='start';c.fillStyle='#1a3458';c.font='500 21px Poppins, Arial';c.fillText(p.name||p.display_name,140,y);y+=40;}y+=18;}const mime=format==='jpg'?'image/jpeg':'image/png',blob=await new Promise(r=>canvas.toBlob(r,mime,.94));if(!blob)throw new Error('Export impossible.');const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=`${(state.title||'liste_france').replace(/[^a-z0-9]+/gi,'_')}.${format==='jpg'?'jpg':'png'}`;a.click();setTimeout(()=>URL.revokeObjectURL(u),3000);status(`${format.toUpperCase()} généré.`,'ok');}catch(err){console.error(err);status(err.message||String(err),'error');}}
  async function waitPlayers(timeout=4000){if(players().length>20)return;await new Promise(resolve=>{let done=false;const finish=()=>{if(done)return;done=true;clearTimeout(timer);window.removeEventListener('bleus:player-registry',finish);resolve();};const timer=setTimeout(finish,timeout);window.addEventListener('bleus:player-registry',finish,{once:true});});}
  async function open(){const m=ensureModal();if(!m)return;state={...state,counts:Object.fromEntries(GROUPS.map(g=>[g.key,g.count])),slots:{},title:'Ma liste France',competitionId:'',competitionName:'',savedId:null};await Promise.allSettled([loadCompetitions(),loadSaved(),waitPlayers()]);render();m.hidden=false;document.body.style.overflow='hidden';}
  window.BLEUS3000_SELECTION_LIST={open,loadSaved};
})();
