/* 3615 Bleus V1.3.10 — Onze type d'un sélectionneur */
(()=>{
'use strict';
const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const db=()=>window.BLEUS3000_SUPABASE||null;
const CACHE_PREFIX='bleus3000.staffBestXi.v1.';
const TTL=6*60*60*1000;
const mem=new Map();
const fmtDate=v=>v?new Date(v+'T12:00:00').toLocaleDateString('fr-FR',{day:'2-digit',month:'2-digit',year:'numeric'}):'—';
const key=(id,f)=>`${id}|${f.start||''}|${f.end||''}|${f.comp||''}`;
function photoUrl(p){if(p?.photo_url)return p.photo_url;if(!p?.photo_path)return '';try{return db()?.storage.from('player-photos').getPublicUrl(p.photo_path).data.publicUrl||'';}catch{return '';}}
function readCache(k){try{const x=JSON.parse(localStorage.getItem(CACHE_PREFIX+k)||'null');return x&&Date.now()-x.at<TTL?x.data:null;}catch{return null;}}
function writeCache(k,data){try{localStorage.setItem(CACHE_PREFIX+k,JSON.stringify({at:Date.now(),data}));}catch{}}
function clearCache(){mem.clear();try{for(let i=localStorage.length-1;i>=0;i--){const k=localStorage.key(i);if(k?.startsWith(CACHE_PREFIX))localStorage.removeItem(k);}}catch{}}
async function load(id,f={}){const k=key(id,f);if(mem.has(k))return mem.get(k);const local=readCache(k);if(local){mem.set(k,local);return local;}const c=db();if(!c)throw new Error('Supabase indisponible');const {data,error}=await c.rpc('get_staff_best_xi_data',{p_staff_id:id,p_start_date:f.start||null,p_end_date:f.end||null,p_competition_key:f.comp||null});if(error)throw error;mem.set(k,data);writeCache(k,data);return data;}
function rankPlayers(data){return (data.players||[]).filter(p=>Number(p.starts)>0).slice().sort((a,b)=>Number(b.starts)-Number(a.starts)||((data.summary?.minutes_reliable?Number(b.minutes_positive)-Number(a.minutes_positive):0))||Number(b.appearances)-Number(a.appearances)||String(b.last_start||'').localeCompare(String(a.last_start||''))||String(a.name).localeCompare(String(b.name),'fr'));}
function posStarts(player,slot){const arr=player.positions||[];if(slot.slug)return Number(arr.find(x=>x.slug===slot.slug)?.starts||0);if(slot.group)return arr.filter(x=>x.group===slot.group).reduce((n,x)=>n+Number(x.starts||0),0);return 0;}
function assignSlots(players,slots,data){const n=slots.length,m=Math.max(players.length,n);if(!n||!players.length)return[];const weights=slots.map(slot=>Array.from({length:m},(_,j)=>{if(j>=players.length)return 0;const p=players[j],ps=posStarts(p,slot);if(ps<=0)return 0;const minutes=data.summary?.minutes_reliable?Number(p.minutes_positive||0):0;const recent=p.last_start?new Date(p.last_start).getTime()/1e13:0;return ps*1e6+minutes*10+Number(p.appearances||0)+recent;}));
// Hungarian minimisation on negative weights, n <= m
const u=Array(n+1).fill(0),v=Array(m+1).fill(0),p=Array(m+1).fill(0),way=Array(m+1).fill(0);
for(let i=1;i<=n;i++){p[0]=i;let j0=0,minv=Array(m+1).fill(Infinity),used=Array(m+1).fill(false);do{used[j0]=true;const i0=p[j0];let delta=Infinity,j1=0;for(let j=1;j<=m;j++)if(!used[j]){const cur=-weights[i0-1][j-1]-u[i0]-v[j];if(cur<minv[j]){minv[j]=cur;way[j]=j0;}if(minv[j]<delta){delta=minv[j];j1=j;}}for(let j=0;j<=m;j++){if(used[j]){u[p[j]]+=delta;v[j]-=delta;}else minv[j]-=delta;}j0=j1;}while(p[j0]!==0);do{const j1=way[j0];p[j0]=p[j1];j0=j1;}while(j0!==0);}
const out=Array(n).fill(null);for(let j=1;j<=m;j++){if(p[j]&&p[j]<=n&&j<=players.length&&weights[p[j]-1][j-1]>0)out[p[j]-1]=players[j-1];}return out;}
function structure(data){const sum=data.summary||{},exact=Number(sum.formation_coverage_pct||0)>=60&&data.top_formation?.slots?.length===11;if(exact)return {kind:'exact',label:data.top_formation.name,slots:data.top_formation.slots};const g=data.generic_shape;if(Number(sum.position_coverage_pct||0)>=80&&Number(sum.complete_position_matches||0)>0&&g){const slots=[];for(let i=0;i<Number(g.gardien||1);i++)slots.push({group:'gardien',label:'Gardien'});for(let i=0;i<Number(g.defense||0);i++)slots.push({group:'defense',label:'Défenseur'});for(let i=0;i<Number(g.milieu||0);i++)slots.push({group:'milieu',label:'Milieu'});for(let i=0;i<Number(g.attaque||0);i++)slots.push({group:'attaque',label:'Attaquant'});return {kind:'generic',label:g.label||'Structure par lignes',slots};}return null;}
function playerCard(p,slot){if(!p)return `<div class="staff-xi-player is-empty"><span class="staff-xi-avatar">?</span><strong>Non déterminé</strong><small>${esc(slot.label||slot.slug||slot.group||'Poste')}</small></div>`;const url=photoUrl(p),ps=posStarts(p,slot);return `<button type="button" class="staff-xi-player" data-staff-xi-player="${esc(p.player_id)}" title="Ouvrir la fiche de ${esc(p.name)}">${url?`<img src="${esc(url)}" alt="" loading="lazy" decoding="async">`:`<span class="staff-xi-avatar">${esc((p.name||'?').split(/\s+/).map(x=>x[0]).join('').slice(0,2))}</span>`}<strong>${esc(p.name)}</strong><small>${esc(slot.label||slot.slug||slot.group||'Poste')}</small><em>${ps} tit. au poste · ${p.starts} au total</em></button>`;}
function detailHtml(data){const players=rankPlayers(data),by=new Map();for(const p of players){for(const pos of p.positions||[]){if(!by.has(pos.label))by.set(pos.label,[]);by.get(pos.label).push({...p,_pos:pos});}}
if(!by.size)return `<div class="staff-xi-global-ranking"><h4>Classement des titularisations</h4>${players.slice(0,20).map((p,i)=>`<button data-staff-xi-player="${esc(p.player_id)}"><b>${i+1}</b><span>${esc(p.name)}</span><em>${p.starts} titularisation${p.starts>1?'s':''}</em></button>`).join('')||'<p>Aucune titularisation renseignée.</p>'}</div>`;
return [...by.entries()].sort((a,b)=>a[0].localeCompare(b[0],'fr')).map(([label,list])=>`<section class="staff-xi-detail-group"><h4>${esc(label)}</h4>${list.sort((a,b)=>Number(b._pos.starts)-Number(a._pos.starts)||Number(b.appearances)-Number(a.appearances)||String(a.name).localeCompare(String(b.name),'fr')).map((p,i)=>`<button data-staff-xi-player="${esc(p.player_id)}"><b>${i+1}</b><span>${esc(p.name)}</span><em>${p._pos.starts} titularisation${p._pos.starts>1?'s':''}</em></button>`).join('')}</section>`).join('');}
function controls(data,staffId){const years=data.years||[],f=data.filters||{};return `<div class="staff-xi-filters" data-staff-xi-filters><label>Année<select data-xi-year><option value="">Toute la période</option>${years.map(y=>`<option value="${y}">${y}</option>`).join('')}</select></label><label>Du<input type="date" data-xi-start value="${esc(f.start_date||'')}"></label><label>Au<input type="date" data-xi-end value="${esc(f.end_date||'')}"></label><label>Compétition<select data-xi-comp><option value="">Toutes</option>${(data.competition_options||[]).map(x=>`<option value="${esc(x.key)}" ${x.key===f.competition_key?'selected':''}>${esc(x.label)} (${x.matches})</option>`).join('')}</select></label><button type="button" data-xi-reset>Réinitialiser</button></div>`;}
function render(host,data,staffId){if(!data?.ok){host.innerHTML='<div class="staff-xi-warning">Impossible de calculer ce module.</div>';return;}const s=data.summary||{},st=structure(data),players=rankPlayers(data),assigned=st?assignSlots(players,st.slots,data):[];const coverage=Number(s.position_coverage_pct||0);host.innerHTML=`${controls(data,staffId)}<div class="staff-xi-summary"><span><b>${s.matches_analyzed||0}</b><small>Matchs analysés</small></span><span><b>${s.players_used||0}</b><small>Joueurs utilisés</small></span><span><b>${s.first_date?fmtDate(s.first_date):'—'} → ${s.last_date?fmtDate(s.last_date):'—'}</b><small>Période</small></span>${st?`<span><b>${esc(st.label)}</b><small>${st.kind==='exact'?'Système le plus utilisé':'Structure observée par lignes'}</small></span>`:''}</div>${st?`<div class="staff-xi-method">Onze composé des joueurs les plus régulièrement titularisés sous ce sélectionneur, uniquement aux postes observés dans les feuilles de match.</div><div class="staff-xi-pitch ${st.kind==='generic'?'is-generic':''}">${st.slots.map((slot,i)=>playerCard(assigned[i],slot)).join('')}</div>`:`<div class="staff-xi-warning"><strong>Onze positionnel non calculable pour le moment.</strong><span>Couverture des postes : ${coverage.toLocaleString('fr-FR')} %. Les feuilles historiques ne renseignent pas encore suffisamment les postes réellement occupés. Aucun poste général de fiche joueur n’est utilisé pour combler artificiellement ces données.</span></div>`}<button type="button" class="staff-xi-detail-toggle" data-xi-detail-toggle>Voir le détail</button><div class="staff-xi-detail" data-xi-detail hidden>${detailHtml(data)}</div>`;bindHost(host,staffId,data);}
function bindHost(host,staffId,data){const rerun=async()=>{const f={start:$('[data-xi-start]',host)?.value||'',end:$('[data-xi-end]',host)?.value||'',comp:$('[data-xi-comp]',host)?.value||''};host.innerHTML='<div class="staff-xi-loading">Calcul du Onze type…</div>';try{render(host,await load(staffId,f),staffId);}catch(e){host.innerHTML=`<div class="staff-xi-warning">${esc(e?.message||e)}</div>`;}};const year=$('[data-xi-year]',host);year?.addEventListener('change',()=>{const y=year.value;$('[data-xi-start]',host).value=y?`${y}-01-01`:'';$('[data-xi-end]',host).value=y?`${y}-12-31`:'';rerun();});$('[data-xi-start]',host)?.addEventListener('change',rerun);$('[data-xi-end]',host)?.addEventListener('change',rerun);$('[data-xi-comp]',host)?.addEventListener('change',rerun);$('[data-xi-reset]',host)?.addEventListener('click',async()=>{host.innerHTML='<div class="staff-xi-loading">Calcul du Onze type…</div>';try{render(host,await load(staffId,{}),staffId);}catch(e){host.innerHTML=`<div class="staff-xi-warning">${esc(e?.message||e)}</div>`;}});$('[data-xi-detail-toggle]',host)?.addEventListener('click',e=>{const d=$('[data-xi-detail]',host);d.hidden=!d.hidden;e.currentTarget.textContent=d.hidden?'Voir le détail':'Masquer le détail';});$$('[data-staff-xi-player]',host).forEach(b=>b.addEventListener('click',()=>window.BLEUS3000_PLAYERS_DB?.openPlayer?.(b.dataset.staffXiPlayer)));}
async function toggle(btn){const id=btn.dataset.staffBestxiToggle,card=btn.closest('.rel-staff-tile'),host=$(`[data-staff-bestxi-host="${CSS.escape(id)}"]`,card);if(!host)return;const opening=host.hidden;host.hidden=!opening;btn.classList.toggle('is-open',opening);btn.querySelector('b').textContent=opening?'−':'＋';if(!opening||host.dataset.loaded)return;host.dataset.loaded='1';host.innerHTML='<div class="staff-xi-loading">Calcul du Onze type…</div>';try{render(host,await load(id,{}),id);}catch(e){host.innerHTML=`<div class="staff-xi-warning">${esc(e?.message||e)}</div>`;host.dataset.loaded='';}}
document.addEventListener('click',e=>{const b=e.target.closest('[data-staff-bestxi-toggle]');if(b){e.preventDefault();toggle(b);}});
window.addEventListener('bleus:data-mutated',e=>{const t=e.detail?.tables||[];if(t.includes('*')||t.some(x=>['matches','match_appearances','players','football_positions','competitions','competition_entities','personnel'].includes(x)))clearCache();});
window.BLEUS3000_STAFF_BEST_XI={clearCache,load};
})();
