(()=>{
  const cfg=window.BLEUS3000_CONFIG||{};
  if(!window.supabase||!cfg.SUPABASE_URL||!cfg.SUPABASE_ANON_KEY)return;
  const db=window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY);
  const state={matches:[],mode:'upcoming',team:'all',canEdit:false};
  const $=s=>document.querySelector(s);
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const flag=(name)=>{const n=String(name||'').toLowerCase(); const map={france:'🇫🇷',islande:'🇮🇸',iceland:'🇮🇸',allemagne:'🇩🇪',germany:'🇩🇪',italie:'🇮🇹',italy:'🇮🇹',espagne:'🇪🇸',spain:'🇪🇸',portugal:'🇵🇹',belgique:'🇧🇪',belgium:'🇧🇪',angleterre:'🏴',england:'🏴',paysbas:'🇳🇱','pays-bas':'🇳🇱',netherlands:'🇳🇱'}; return map[n.replace(/\s+/g,'')]||map[n]||'🌍'};
  const frDate=(iso)=>{const d=new Date(iso);return new Intl.DateTimeFormat('fr-FR',{weekday:'long',day:'2-digit',month:'long',year:'numeric',hour:'2-digit',minute:'2-digit',hour12:false,timeZone:'Europe/Paris'}).format(d).replace(' à ',' - ').replace(':','H').replace(/^./,c=>c.toUpperCase())};
  const selectionLabel=m=>m.selection_teams?.name?.replace(/ Masculin$/,'')||m.selection_category||'France';
  const opponent=m=>m.opponents?.name||'Adversaire à confirmer';
  const teams=m=>m.home_away==='away'?[opponent(m),selectionLabel(m)]:[selectionLabel(m),opponent(m)];
  const score=m=>m.france_score==null||m.opponent_score==null?'':(m.home_away==='away'?`${m.opponent_score} - ${m.france_score}`:`${m.france_score} - ${m.opponent_score}`);
  const place=m=>[m.places?.name,m.places?.city].filter(Boolean).join(', ');
  function row(m){const [a,b]=teams(m), s=score(m), past=new Date(m.match_date)<new Date(); return `<article class="calendar-row" data-calendar-id="${esc(m.id)}"><div class="calendar-date">${esc(frDate(m.match_date))}</div><div class="calendar-fixture"><span class="calendar-flag">${flag(a.replace(/\s+(U\d+|Espoirs|A).*$/i,''))}</span><span>${esc(a)}</span><span>${s?`<strong class="calendar-score">${esc(s)}</strong>`:'–'}</span><span>${esc(b)}</span><span class="calendar-flag">${flag(b.replace(/\s+(U\d+|Espoirs|A).*$/i,''))}</span></div>${place(m)?`<div class="calendar-place">${esc(place(m))}</div>`:''}<div class="calendar-meta"><span class="calendar-tv">📺 ${esc(m.broadcast_text||'Diffusion à confirmer')}</span>${m.broadcast_url?`<a class="calendar-stream" href="${esc(m.broadcast_url)}" target="_blank" rel="noopener noreferrer" title="Voir la diffusion internet" aria-label="Voir la diffusion internet">↗</a>`:''}<span class="calendar-tag">${esc(selectionLabel(m))}</span>${m.competitions?.name?`<span class="calendar-tag competition">${esc(m.competitions.name)}</span>`:''}${state.canEdit?`<button class="calendar-edit-btn" type="button" data-calendar-edit="${esc(m.id)}">Modifier diffusion</button>`:''}<span class="calendar-state">${m.data_state==='api'?'API':m.data_state==='locked'?'Verrouillé':past?'Historique vérifié':'Vérifié'}</span></div></article>`}
  function filtered(){const now=Date.now();return state.matches.filter(m=>(state.mode==='past'?new Date(m.match_date).getTime()<now:new Date(m.match_date).getTime()>=now)&&(state.team==='all'||String(m.selection_team_id)===state.team)).sort((a,b)=>state.mode==='past'?new Date(b.match_date)-new Date(a.match_date):new Date(a.match_date)-new Date(b.match_date));}
  function render(){const all=filtered();const home=$('#calendarHomeList'); if(home)home.innerHTML=(state.matches.filter(m=>new Date(m.match_date)>=new Date()).sort((a,b)=>new Date(a.match_date)-new Date(b.match_date)).slice(0,5).map(row).join('')||'<div class="calendar-empty">Aucun prochain match enregistré.</div>'); const full=$('#calendarFullList');if(full)full.innerHTML=all.map(row).join('')||'<div class="calendar-empty">Aucun match pour ce filtre.</div>';}
  async function load(){const q=`id,match_date,selection_category,selection_team_id,home_away,france_score,opponent_score,status,broadcast_text,broadcast_url,data_state,provider,provider_fixture_id,opponents(name,fifa_code),competitions(name,code),places(name,city,country),selection_teams(name,code,category)`;let {data,error}=await db.from('matches').select(q).order('match_date',{ascending:false}).limit(2500);if(error){console.warn('Calendrier Bleus 3000',error);['#calendarHomeList','#calendarFullList'].forEach(s=>{const e=$(s);if(e)e.innerHTML='<div class="calendar-empty">Calendrier indisponible · migration V1.1.30 à appliquer.</div>'});return;}state.matches=data||[];render();populateTeams();}
  async function permissions(){const {data:{user}}=await db.auth.getUser();if(!user)return;const {data}=await db.from('profiles').select('role').eq('id',user.id).maybeSingle();state.canEdit=['editor','admin','superadmin'].includes(data?.role);render();}
  function populateTeams(){const sel=$('#calendarTeamFilter');if(!sel)return;const opts=[...new Map(state.matches.filter(m=>m.selection_team_id).map(m=>[m.selection_team_id,selectionLabel(m)])).entries()].sort((a,b)=>a[1].localeCompare(b[1],'fr'));sel.innerHTML='<option value="all">Toutes les sélections</option>'+opts.map(([id,n])=>`<option value="${esc(id)}">${esc(n)}</option>`).join('');}
  function openModal(){const m=$('#calendarModal');if(m){m.hidden=false;document.body.classList.add('modal-open');render();}}
  function closeModal(){const m=$('#calendarModal');if(m){m.hidden=true;document.body.classList.remove('modal-open')}}
  function openEdit(id){const m=state.matches.find(x=>x.id===id);if(!m||!state.canEdit)return;$('#calendarEditMatchId').value=id;$('#calendarEditBroadcast').value=m.broadcast_text||'';$('#calendarEditUrl').value=m.broadcast_url||'';$('#calendarEditModal').hidden=false;}
  document.addEventListener('click',e=>{const open=e.target.closest('#calendarToolbarBtn,#calendarOpenAll');if(open){openModal();return}const tab=e.target.closest('[data-calendar-mode]');if(tab){state.mode=tab.dataset.calendarMode;document.querySelectorAll('[data-calendar-mode]').forEach(x=>x.classList.toggle('is-active',x===tab));render();return}const edit=e.target.closest('[data-calendar-edit]');if(edit){openEdit(edit.dataset.calendarEdit);return}if(e.target.closest('[data-calendar-close]'))closeModal();});
  $('#calendarTeamFilter')?.addEventListener('change',e=>{state.team=e.target.value;render()});
  $('#calendarEditForm')?.addEventListener('submit',async e=>{e.preventDefault();const id=$('#calendarEditMatchId').value;const broadcast_text=$('#calendarEditBroadcast').value.trim()||null;const broadcast_url=$('#calendarEditUrl').value.trim()||null;const {error}=await db.from('matches').update({broadcast_text,broadcast_url,updated_at:new Date().toISOString()}).eq('id',id);if(error){alert('Modification impossible : '+error.message);return}const m=state.matches.find(x=>x.id===id);if(m){m.broadcast_text=broadcast_text;m.broadcast_url=broadcast_url}$('#calendarEditModal').hidden=true;render();});
  load();permissions();
})();
