/* Bleus 3000 V1.1.36 — Calendrier relationnel + TheSportsDB + corrections manuelles + tags globaux + drapeaux SVG */
(()=>{
  'use strict';
  const state={matches:[],mode:'upcoming',team:'all',canEdit:false,live:new Map(),liveTimer:null};
  const $=s=>document.querySelector(s);
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const store=()=>window.BLEUS3000_RELATIONAL_REFS;
  const eff=(m,k)=>store()?.effective?store().effective(m,k):m?.[k];
  const base=(m,k)=>store()?.baseValue?store().baseValue(m,k):m?.[k];
  const parseDate=v=>{const d=new Date(v);return Number.isNaN(+d)?null:d;};
  const flagImg=name=>window.BLEUS3000_FLAGS?.img?.(name,'calendar-svg-flag')||'<span class="calendar-svg-flag is-missing">◌</span>';
  const frDate=iso=>{const d=parseDate(iso);if(!d)return String(iso||'Date à confirmer');return new Intl.DateTimeFormat('fr-FR',{weekday:'long',day:'2-digit',month:'long',year:'numeric',hour:'2-digit',minute:'2-digit',hour12:false,timeZone:'Europe/Paris'}).format(d).replace(' à ',' - ').replace(':','H').replace(/^./,c=>c.toUpperCase());};
  const selectionLabel=m=>m.selection?.name?.replace(/ Masculin$/,'').replace(/ Féminine$/,' F')||m.selection_category||'France';
  const opponent=m=>eff(m,'opponent_name')||'Adversaire à confirmer';
  const teams=m=>m.home_away==='away'?[opponent(m),selectionLabel(m)]:[selectionLabel(m),opponent(m)];
  const liveFor=m=>m.provider==='thesportsdb'&&m.provider_fixture_id?state.live.get(String(m.provider_fixture_id)):null;
  const score=m=>{const l=liveFor(m);if(l){const home=Number(l.intHomeScore),away=Number(l.intAwayScore);if(Number.isFinite(home)&&Number.isFinite(away))return `${home} - ${away}`;}const a=eff(m,'france_score'),b=eff(m,'opponent_score');if(a==null||b==null||a===''||b==='')return '';return m.home_away==='away'?`${b} - ${a}`:`${a} - ${b}`;};
  const place=m=>[eff(m,'venue_name'),eff(m,'city')].filter(Boolean).join(', ');
  const isLive=m=>!!liveFor(m)||['1H','2H','HT','ET','P','LIVE','IN PLAY','IN_PLAY'].includes(String(eff(m,'status')||'').toUpperCase());
  const manual=m=>Object.keys(m.manual_overrides||{}).length>0;
  const tagById=id=>id?store()?.getTag?.(id):null;
  const sectionTag=m=>tagById(eff(m,'selection_tag_id'));
  const competitionTag=m=>tagById(eff(m,'competition_tag_id'));
  function fallbackTag(label,cls=''){return `<span class="calendar-tag ${cls}">${esc(label)}</span>`;}
  function tagChip(t,cls=''){
    if(!t)return '';
    if(window.BLEUS3000_TAGS?.chipHtml)return window.BLEUS3000_TAGS.chipHtml(t,`calendar-global-tag ${cls}`.trim());
    const bg=t.appearance==='solid'?(t.color_start||'#082654'):`linear-gradient(${Number(t.gradient_angle||135)}deg,${t.color_start||'#082654'},${t.color_end||'#2563eb'})`;
    return `<span class="calendar-tag ${cls}" style="background:${bg};color:${esc(t.text_color||'#fff')};border-color:${esc(t.border_color||'#082654')}">${esc(t.icon_text||'🏷️')} ${esc(t.label_text||'TAG')}</span>`;
  }
  function sectionChip(m){const t=sectionTag(m);return t?tagChip(t,'section'):fallbackTag(selectionLabel(m),'section');}
  function competitionChip(m){const t=competitionTag(m);if(t)return tagChip(t,'competition');const n=eff(m,'competition_name');return n?fallbackTag(n,'competition'):'';}
  function statusLabel(m){const l=liveFor(m);if(l){const p=String(l.strProgress||'').trim();const s=String(l.strStatus||'LIVE').toUpperCase();return `<span class="calendar-live"><i></i> LIVE${p?` · ${esc(p)}${/^\d+$/.test(p)?"'":''}`:s==='HT'?' · MI-TEMPS':''}</span>`;}const s=String(eff(m,'status')||'').toUpperCase();if(['FT','MATCH FINISHED','FINISHED'].includes(s))return '<span class="calendar-finished">✓ TERMINÉ</span>';if(/POSTP/.test(s))return '<span class="calendar-postponed">● REPORTÉ</span>';if(/CANC/.test(s))return '<span class="calendar-cancelled">● ANNULÉ</span>';return ''}
  function row(m){const [a,b]=teams(m),s=score(m),past=parseDate(eff(m,'match_date'))?.getTime()<Date.now();const tv=eff(m,'broadcast_text')||'Diffusion à confirmer',url=eff(m,'broadcast_url');return `<article class="calendar-row ${isLive(m)?'is-live':''}" data-calendar-id="${esc(m.id)}"><div class="calendar-date">${esc(frDate(eff(m,'match_date')))}</div><div class="calendar-fixture"><span class="calendar-team"><span class="calendar-flag">${flagImg(a)}</span><span>${esc(a)}</span></span><span class="calendar-separator">${s?`<strong class="calendar-score">${esc(s)}</strong>`:'–'}</span><span class="calendar-team"><span>${esc(b)}</span><span class="calendar-flag">${flagImg(b)}</span></span>${statusLabel(m)}</div>${place(m)?`<div class="calendar-place">${esc(place(m))}</div>`:''}<div class="calendar-meta"><span class="calendar-tv">📺 ${esc(tv)}</span>${url?`<a class="calendar-stream" href="${esc(url)}" target="_blank" rel="noopener noreferrer" title="Voir la diffusion internet" aria-label="Voir la diffusion internet">↗</a>`:''}${sectionChip(m)}${competitionChip(m)}${manual(m)?'<span class="calendar-manual">✎ manuel</span>':''}${state.canEdit?`<button class="calendar-edit-btn" type="button" data-calendar-edit="${esc(m.id)}">Modifier</button>`:''}<span class="calendar-state">${m.provider==='thesportsdb'?'TheSportsDB':m.data_state==='locked'?'Verrouillé':past?'Historique vérifié':'Bleus 3000'}</span></div></article>`}
  function filtered(){const now=Date.now();return state.matches.filter(m=>{const d=parseDate(eff(m,'match_date'))?.getTime()||0;const live=isLive(m);const temporal=state.mode==='past'?(!live&&d<now):(live||d>=now);return temporal&&(state.team==='all'||String(m.selection_team_id)===state.team)}).sort((a,b)=>state.mode==='past'?(parseDate(eff(b,'match_date'))-parseDate(eff(a,'match_date'))):(parseDate(eff(a,'match_date'))-parseDate(eff(b,'match_date'))));}
  function render(){const all=filtered();const home=$('#calendarHomeList');if(home){const up=state.matches.filter(m=>isLive(m)||(parseDate(eff(m,'match_date'))?.getTime()||0)>=Date.now()).sort((a,b)=>{if(isLive(a)!==isLive(b))return isLive(a)?-1:1;return parseDate(eff(a,'match_date'))-parseDate(eff(b,'match_date'));}).slice(0,5);home.innerHTML=up.map(row).join('')||'<div class="calendar-empty">Aucun prochain match enregistré.</div>';}const full=$('#calendarFullList');if(full)full.innerHTML=all.map(row).join('')||'<div class="calendar-empty">Aucun match pour ce filtre.</div>';}
  async function load(){try{state.matches=await store()?.load?.()||[];populateTeams();render();}catch(error){console.warn('Calendrier Bleus 3000',error);['#calendarHomeList','#calendarFullList'].forEach(s=>{const e=$(s);if(e)e.innerHTML='<div class="calendar-empty">Calendrier indisponible.</div>'});}}
  function setPermissions(role){state.canEdit=['editor','admin','superadmin'].includes(String(role||'').toLowerCase());render();}
  async function permissions(){setPermissions(window.C3K_ACCOUNT_STATE?.role);}
  function populateTeams(){const sel=$('#calendarTeamFilter');if(!sel)return;const opts=[...new Map(state.matches.filter(m=>m.selection_team_id).map(m=>[m.selection_team_id,selectionLabel(m)])).entries()].sort((a,b)=>a[1].localeCompare(b[1],'fr'));const prev=state.team;sel.innerHTML='<option value="all">Toutes les sélections</option>'+opts.map(([id,n])=>`<option value="${esc(id)}">${esc(n)}</option>`).join('');if([...sel.options].some(o=>o.value===prev))sel.value=prev;}
  function openModal(){const m=$('#calendarModal');if(m){m.hidden=false;document.body.classList.add('modal-open');render();pollLive();}}
  function closeModal(){const m=$('#calendarModal');if(m){m.hidden=true;document.body.classList.remove('modal-open')}}
  const toInputDate=iso=>{const d=parseDate(iso);if(!d)return '';const p=new Intl.DateTimeFormat('sv-SE',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false,timeZone:'Europe/Paris'}).format(d);return p.replace(' ','T');};
  const tagOption=(t,selected)=>`<option value="${esc(t.id)}" ${String(t.id)===String(selected)?'selected':''}>${esc(t.label_text)}</option>`;
  function fillTagSelects(m){
    const sec=$('#calendarEditSelectionTag'),comp=$('#calendarEditCompetitionTag');
    if(sec){const baseId=base(m,'selection_tag_id')||'';const current=eff(m,'selection_tag_id')||'';const rows=(store()?.getSectionTags?.()||[]).sort((a,b)=>String(a.label_text).localeCompare(String(b.label_text),'fr'));sec.innerHTML=`<option value="">Automatique${baseId&&tagById(baseId)?` · ${esc(tagById(baseId).label_text)}`:''}</option>`+rows.map(t=>tagOption(t,current)).join('');if(current&&[...sec.options].some(o=>o.value===String(current)))sec.value=String(current);else sec.value='';}
    if(comp){const baseId=base(m,'competition_tag_id')||'';const current=eff(m,'competition_tag_id')||'';const rows=(store()?.getCompetitionTags?.()||[]).sort((a,b)=>String(a.label_text).localeCompare(String(b.label_text),'fr'));comp.innerHTML=`<option value="">Automatique${baseId&&tagById(baseId)?` · ${esc(tagById(baseId).label_text)}`:''}</option>`+rows.map(t=>tagOption(t,current)).join('');if(current&&[...comp.options].some(o=>o.value===String(current)))comp.value=String(current);else comp.value='';}
  }
  function openEdit(id){const m=store()?.getMatch?.(id)||state.matches.find(x=>x.id===id);if(!m)return;if(!state.canEdit){alert('Modification réservée aux éditeurs et administrateurs.');return;}$('#calendarEditMatchId').value=id;$('#calendarEditDate').value=toInputDate(eff(m,'match_date'));$('#calendarEditOpponent').value=eff(m,'opponent_name')||'';$('#calendarEditVenue').value=eff(m,'venue_name')||'';$('#calendarEditCity').value=eff(m,'city')||'';$('#calendarEditCompetition').value=eff(m,'competition_name')||'';$('#calendarEditBroadcast').value=eff(m,'broadcast_text')||'';$('#calendarEditUrl').value=eff(m,'broadcast_url')||'';$('#calendarEditFranceScore').value=eff(m,'france_score')??'';$('#calendarEditOpponentScore').value=eff(m,'opponent_score')??'';fillTagSelects(m);$('#calendarEditModal').hidden=false;}
  const normText=v=>String(v??'').trim();
  const normNum=v=>v===''||v==null?null:Number(v);
  function buildOverrides(m,values){const next={...(m.manual_overrides||{})};for(const [key,value] of Object.entries(values)){const raw=base(m,key);let sameAsBase=false;if(key==='match_date'){const a=parseDate(value),b=parseDate(raw);sameAsBase=!!a&&!!b&&Math.abs(+a-+b)<60000;}else if(key==='france_score'||key==='opponent_score')sameAsBase=normNum(value)===normNum(raw);else if(key==='selection_tag_id'||key==='competition_tag_id'){if(!value){delete next[key];continue;}sameAsBase=String(value)===String(raw||'');}else sameAsBase=normText(value)===normText(raw);if(sameAsBase)delete next[key];else next[key]=(key==='france_score'||key==='opponent_score')?normNum(value):value;}return next;}
  async function pollLive(){try{const r=await fetch('/api/sportsdb-live',{headers:{accept:'application/json'}});if(!r.ok)return;const data=await r.json();state.live=new Map((data.livescore||[]).map(x=>[String(x.idEvent),x]));render();}catch{} }
  function setupLive(){pollLive();state.liveTimer=setInterval(()=>{if(document.visibilityState==='visible')pollLive();},120000);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')pollLive();});}
  document.addEventListener('click',e=>{const open=e.target.closest('#calendarToolbarBtn,#calendarOpenAll');if(open){openModal();return}const tab=e.target.closest('[data-calendar-mode]');if(tab){state.mode=tab.dataset.calendarMode;document.querySelectorAll('[data-calendar-mode]').forEach(x=>x.classList.toggle('is-active',x===tab));render();return}const edit=e.target.closest('[data-calendar-edit]');if(edit){openEdit(edit.dataset.calendarEdit);return}if(e.target.closest('[data-calendar-close]'))closeModal();});
  $('#calendarTeamFilter')?.addEventListener('change',e=>{state.team=e.target.value;render()});
  $('#calendarEditReset')?.addEventListener('click',async()=>{const id=$('#calendarEditMatchId').value;if(!id)return;const db=window.BLEUS3000_SUPABASE;if(!db)return;const {error}=await db.from('matches').update({manual_overrides:{},updated_at:new Date().toISOString()}).eq('id',id);if(error){alert('Réinitialisation impossible : '+error.message);return;}store()?.applyLocalOverride?.(id,{});$('#calendarEditModal').hidden=true;render();window.BLEUS3000_RELATIONAL_REFS?.render?.('matchs',$('#referenceSearch')?.value||'');});
  $('#calendarEditForm')?.addEventListener('submit',async e=>{e.preventDefault();const id=$('#calendarEditMatchId').value,m=store()?.getMatch?.(id);const db=window.BLEUS3000_SUPABASE;if(!m||!db)return;const localDate=$('#calendarEditDate').value;const dateValue=localDate?new Date(localDate).toISOString():'';const values={match_date:dateValue,opponent_name:$('#calendarEditOpponent').value.trim(),venue_name:$('#calendarEditVenue').value.trim(),city:$('#calendarEditCity').value.trim(),competition_name:$('#calendarEditCompetition').value.trim(),selection_tag_id:$('#calendarEditSelectionTag').value,competition_tag_id:$('#calendarEditCompetitionTag').value,broadcast_text:$('#calendarEditBroadcast').value.trim(),broadcast_url:$('#calendarEditUrl').value.trim(),france_score:$('#calendarEditFranceScore').value,opponent_score:$('#calendarEditOpponentScore').value};const manual_overrides=buildOverrides(m,values);const {error}=await db.from('matches').update({manual_overrides,updated_at:new Date().toISOString()}).eq('id',id);if(error){alert('Modification impossible : '+error.message);return;}m.manual_overrides=manual_overrides;$('#calendarEditModal').hidden=true;render();window.BLEUS3000_RELATIONAL_REFS?.render?.('matchs',$('#referenceSearch')?.value||'');});
  window.addEventListener('c3k:account-state',e=>setPermissions(e.detail?.role));
  window.addEventListener('bleus:matches-ready',e=>{state.matches=e.detail?.matches||[];populateTeams();render();});
  window.BLEUS3000_CALENDAR={open:openModal,openEdit,refresh:load,pollLive};
  load();permissions();setupLive();
})();
