/* Bleus 3000 V1.1.2 — mur des membres : messages courts + likes, sans épinglage */
(() => {
  'use strict';
  const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const localKey='bleus3000.member.wall.local.v2';
  let host=null,open=false,rows=[],likes=new Map(),channel=null;
  const state=()=>window.C3K_ACCOUNT_STATE||{}; const client=()=>window.BLEUS3000_SUPABASE;
  const myId=()=>state().profile?.id||'local-demo'; const canModerate=()=>['admin','superadmin'].includes(state().profile?.role);
  const fmt=d=>{try{return new Intl.DateTimeFormat('fr-FR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(d));}catch{return ''}};
  function localRows(){try{return JSON.parse(localStorage.getItem(localKey)||'[]');}catch{return [];}}
  function saveLocal(){localStorage.setItem(localKey,JSON.stringify(rows));}
  function ensure(){const shell=$('#c3kV8AccountShell');if(!shell)return null;const rail=$('#c3kTopLeftRail')||shell.parentElement;if(!host){host=document.createElement('section');host.id='c3kMemberWall';host.className='c3k-member-wall';rail.appendChild(host);}return host;}
  function styleVars(){const p=state().profile?.postit_style||{};const c1=p.color_start||'#DFEEFF',c2=p.color_end||'#BFE3F3',ink=p.text_color||'#17375E',border=p.border_color||'#8FB4EA',radius=Number(p.border_radius)||9;return `--wall-bg:linear-gradient(135deg,${c1},${c2});--wall-tile:${c1};--wall-ink:${ink};--wall-border:${border};--wall-radius:${radius}px`;}
  function likesFor(id){return likes.get(id)||[];}
  async function load(){ensure();if(!state().profile){host.hidden=true;return;}host.hidden=false;const c=client();if(c&&state().session?.user){const [p,l]=await Promise.all([c.from('member_wall_posts').select('*').order('created_at',{ascending:false}).limit(40),c.from('member_wall_likes').select('*').order('created_at',{ascending:true})]);rows=p.data||[];likes.clear();(l.data||[]).forEach(x=>{const a=likes.get(x.post_id)||[];a.push(x);likes.set(x.post_id,a);});}else{rows=localRows();likes.clear();rows.forEach(r=>(r.likes||[]).forEach(uid=>{const a=likes.get(r.id)||[];a.push({user_id:uid});likes.set(r.id,a);}));}render();}
  function render(){ensure();if(!state().profile){host.hidden=true;return;}const social=window.C3K_SOCIAL_PROFILE;host.hidden=false;host.classList.toggle('is-open',open);host.innerHTML=`<div class="c3k-member-wall-collapsed"><button type="button" class="c3k-member-wall-toggle" data-wall-toggle><span>🗒 Mur des membres</span><span class="c3k-wall-toggle-meta">${rows.length}</span><span class="c3k-wall-chevron">${open?'▴':'▾'}</span></button></div><div class="c3k-member-wall-panel" ${open?'':'hidden'}><div class="c3k-member-wall-toolbar"><small>Messages courts · 140 caractères</small><button type="button" data-wall-browser>🔔 Notifications</button></div><div class="c3k-member-wall-list">${rows.map(r=>{const mine=likesFor(r.id).some(x=>x.user_id===myId()),actions=[];if(r.author_id===myId()||canModerate())actions.push(`<button data-delete="${r.id}">Supprimer</button>`);return `<article class="c3k-member-postit" style="${styleVars()}"><div class="c3k-member-postit-author"><strong>${esc(r.author_username||'Membre')}</strong>${social?.roleBadgeHtml?.(r.author_role||'user',social?.getMemberLabel?.(r.author_id))||''}</div><div class="c3k-member-postit-body"><div class="c3k-member-postit-message">${esc(r.message)}</div><div class="c3k-member-postit-meta"><span>${fmt(r.created_at)}</span><span class="c3k-member-postit-reactions"><button class="c3k-wall-like ${mine?'is-liked':''}" data-like="${r.id}" type="button">♥</button><span>${likesFor(r.id).length}</span></span><span class="c3k-member-postit-actions">${actions.join('')}</span></div></div></article>`;}).join('')||'<div class="c3k-member-wall-empty">Aucun message pour le moment.</div>'}</div><form class="c3k-member-wall-compose" id="c3kMemberWallForm"><textarea id="c3kMemberWallText" maxlength="140" placeholder="Écrire au mur des membres…"></textarea><div class="c3k-wall-style-note">🎨 Style défini dans Profil → Personnalisation</div><div class="c3k-member-wall-compose-row"><span class="c3k-member-wall-counter" id="c3kMemberWallCounter">0 / 140</span><button type="submit">Publier</button></div></form></div>`;$('[data-wall-toggle]',host)?.addEventListener('click',()=>{open=!open;render();});$('[data-wall-browser]',host)?.addEventListener('click',async()=>{if(!('Notification'in window))return alert('Notifications navigateur indisponibles.');const r=await Notification.requestPermission();if(r==='granted')alert('Notifications activées.');});const ta=$('#c3kMemberWallText',host),counter=$('#c3kMemberWallCounter',host);ta?.addEventListener('input',()=>counter.textContent=`${ta.value.length} / 140`);$('#c3kMemberWallForm',host)?.addEventListener('submit',publish);$$('[data-like]',host).forEach(b=>b.addEventListener('click',()=>toggleLike(b.dataset.like)));$$('[data-delete]',host).forEach(b=>b.addEventListener('click',()=>remove(b.dataset.delete)));}
  async function publish(e){e.preventDefault();const ta=$('#c3kMemberWallText',host),msg=ta.value.trim();if(!msg)return;const p=state().profile,c=client();if(c&&state().session?.user){const {error}=await c.from('member_wall_posts').insert({message:msg});if(error)return alert(error.message);}else{rows.unshift({id:crypto.randomUUID?.()||String(Date.now()),author_id:myId(),author_username:p.username||p.first_name||'Membre',author_role:p.role||'user',message:msg,created_at:new Date().toISOString(),likes:[]});saveLocal();}ta.value='';await load();}
  async function toggleLike(id){const c=client(),mine=likesFor(id).some(x=>x.user_id===myId());if(c&&state().session?.user){const q=mine?c.from('member_wall_likes').delete().eq('post_id',id).eq('user_id',myId()):c.from('member_wall_likes').insert({post_id:id,user_id:myId(),username:state().profile.username||'Membre',first_name:state().profile.first_name||null});const {error}=await q;if(error)return alert(error.message);}else{const r=rows.find(x=>x.id===id);r.likes=r.likes||[];r.likes=mine?r.likes.filter(x=>x!==myId()):[...new Set([...r.likes,myId()])];saveLocal();}await load();}
  async function remove(id){if(!confirm('Supprimer ce message ?'))return;const c=client();if(c&&state().session?.user){const {error}=await c.from('member_wall_posts').delete().eq('id',id);if(error)return alert(error.message);}else{rows=rows.filter(x=>x.id!==id);saveLocal();}await load();}
  function subscribe(){const c=client();if(!c||channel||!state().session?.user)return;channel=c.channel('b3k-member-wall').on('postgres_changes',{event:'*',schema:'public',table:'member_wall_posts'},()=>load()).on('postgres_changes',{event:'*',schema:'public',table:'member_wall_likes'},()=>load()).subscribe();}
  function accountChanged(){if(state().profile){load();subscribe();}else if(host)host.hidden=true;}
  function init(){ensure();accountChanged();window.addEventListener('c3k:account-state',accountChanged);}
  window.C3K_MEMBER_WALL={refresh:load,open:()=>{open=true;render();}};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
