/* 3615 Bleus V1.3.8 — Actus accueil autonomes */
(()=>{
  'use strict';
  const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const db=()=>window.BLEUS3000_SUPABASE;
  const canEdit=()=>['admin','superadmin'].includes(String(window.C3K_ACCOUNT_STATE?.profile?.role||window.C3K_ACCOUNT_STATE?.role||'').toLowerCase());
  const state={loaded:false,loading:null,rows:[],links:[],channels:[],mounted:null,page:1,pageSize:3};
  const fmt=v=>{if(!v)return '';const d=new Date(v);if(Number.isNaN(+d))return String(v);return new Intl.DateTimeFormat('fr-FR',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit',timeZone:'Europe/Paris'}).format(d).replace(':','h');};
  function sortRows(rows){const now=Date.now();return [...rows].sort((a,b)=>{if(Boolean(a.homepage_pinned)!==Boolean(b.homepage_pinned))return a.homepage_pinned?-1:1;if(a.homepage_pinned&&b.homepage_pinned){const ap=+new Date(a.homepage_pinned_at||0),bp=+new Date(b.homepage_pinned_at||0);if(ap!==bp)return bp-ap;}const at=a.event_at?+new Date(a.event_at):Infinity,bt=b.event_at?+new Date(b.event_at):Infinity,af=at>=now,bf=bt>=now;if(af!==bf)return af?-1:1;if(af)return at-bt;return bt-at;});}
  async function load(force=false){if(state.loaded&&!force)return state;if(state.loading)return state.loading;const c=db();if(!c)return state;state.loading=(async()=>{const [a,l,ch]=await Promise.all([c.from('homepage_news').select('*'),c.from('homepage_news_broadcast_channels').select('*').order('sort_order'),c.from('broadcast_channels').select('*').eq('active',true).order('name')]);if(a.error)throw a.error;if(l.error)throw l.error;if(ch.error)throw ch.error;state.rows=sortRows(a.data||[]);state.links=l.data||[];state.channels=ch.data||[];state.loaded=true;return state;})().finally(()=>state.loading=null);return state.loading;}
  const linksFor=id=>state.links.filter(x=>String(x.homepage_news_id)===String(id));
  function channelHtml(link){const ch=state.channels.find(x=>String(x.id)===String(link.broadcast_channel_id)),label=ch?.name||'Diffusion',html=window.BLEUS3000_BROADCASTS?.renderText?.(label)||`📺 ${esc(label)}`;return `<span class="home-news-channel">${html}</span>`;}
  function tile(r){const actions=[];if(r.link_url)actions.push(`<a href="${esc(r.link_url)}" target="_blank" rel="noopener noreferrer">↗ Voir le lien</a>`);if(r.youtube_url)actions.push(`<a class="home-news-live" href="${esc(r.youtube_url)}" target="_blank" rel="noopener noreferrer">▶ Live YouTube</a>`);actions.push(...linksFor(r.id).map(channelHtml));const upcoming=Boolean(r.upcoming_event)&&r.event_at&&(+new Date(r.event_at)>Date.now());return `<article class="home-news-tile ${r.homepage_pinned?'is-pinned':''}" data-home-news-id="${esc(r.id)}"><div class="home-news-top"><span class="home-news-label">ACTU</span>${r.homepage_pinned?'<span class="home-news-pin-tag">↑ ÉPINGLÉE</span>':''}${upcoming?'<span class="home-news-upcoming-tag">ÉVÈNEMENT À VENIR</span>':''}${r.event_at?`<time class="home-news-date">${esc(fmt(r.event_at))}</time>`:''}${canEdit()?`<span class="home-news-admin-actions"><button type="button" class="secondary-btn ${r.homepage_pinned?'is-active':''}" data-home-news-pin="${esc(r.id)}" title="${r.homepage_pinned?'Retirer l’épinglage':'Épingler cette actu'}">↑</button><button type="button" class="secondary-btn" data-home-news-edit="${esc(r.id)}">Modifier</button><button type="button" class="secondary-btn" data-home-news-delete="${esc(r.id)}">×</button></span>`:''}</div><strong class="home-news-title">${esc(r.title)}</strong>${r.note?`<div class="home-news-note">${esc(r.note)}</div>`:''}${actions.length?`<div class="home-news-actions">${actions.join('')}</div>`:''}${r.active===false?'<small>Masquée au public</small>':''}</article>`;}
  async function render(container){await load();if(!container||!container.isConnected)return;const rows=state.rows.filter(r=>r.active!==false||canEdit()),pages=Math.max(1,Math.ceil(rows.length/state.pageSize));state.page=Math.min(Math.max(1,state.page),pages);const start=(state.page-1)*state.pageSize,shown=rows.slice(start,start+state.pageSize);container.innerHTML=shown.length?shown.map(tile).join(''):'<div class="home-events-empty">Aucune actu pour le moment.</div>';renderPagination(rows.length);}
  function renderPagination(total){const nav=$('#gatheringHomeEventsPagination');if(!nav)return;const pages=Math.max(1,Math.ceil(total/state.pageSize));if(pages<=1){nav.hidden=true;nav.innerHTML='';return;}nav.hidden=false;nav.innerHTML=`<button type="button" data-home-news-page="${Math.max(1,state.page-1)}" ${state.page===1?'disabled':''}>‹</button><span class="calendar-home-page-status">${state.page} / ${pages}</span><button type="button" data-home-news-page="${Math.min(pages,state.page+1)}" ${state.page===pages?'disabled':''}>›</button>`;nav.querySelectorAll('[data-home-news-page]').forEach(b=>b.addEventListener('click',()=>{if(b.disabled)return;state.page=Number(b.dataset.homeNewsPage)||1;render(state.mounted);}));}
  function mount(host=$('#gatheringHomeEvents')){if(!host)return;let c=$('.home-news-list',host);if(!c){c=document.createElement('div');c.className='home-news-list';host.prepend(c);}state.mounted=c;render(c).catch(console.warn);ensureAdminButton();}
  function ensureAdminButton(){const head=$('.home-events-head');if(!head)return;const actions=$('.home-events-actions',head)||head;let b=$('#homeNewsAddBtn',head);if(canEdit()){if(!b){b=document.createElement('button');b.id='homeNewsAddBtn';b.className='home-events-open';b.type='button';b.textContent='＋ Actu';const gather=$('#homeEventsOpenGatherings',actions);actions.insertBefore(b,gather||null);}}else b?.remove();}
  function modal(){let m=$('#homeNewsEditor');if(m)return m;document.body.insertAdjacentHTML('beforeend',`<div class="modal-backdrop" id="homeNewsEditor" hidden><section class="modal-dialog" style="width:min(680px,100%)"><header class="modal-head"><div><h2>Tuile Actu</h2><p>Accueil uniquement · indépendante des rassemblements</p></div><button class="modal-close" type="button" data-home-news-close>×</button></header><div class="modal-body"><form id="homeNewsForm"><input type="hidden" name="id"><div class="home-news-editor-grid"><label class="is-wide">Titre<input name="title" maxlength="180" required></label><label>Date / heure<input name="event_at" type="datetime-local"></label><label>Statut<select name="active"><option value="true">Visible</option><option value="false">Masquée</option></select></label><div><strong>Tag événement</strong><label class="home-news-check"><input name="upcoming_event" type="checkbox"> <span>Évènement à venir</span></label></div><label class="is-wide">Petite note<textarea name="note" maxlength="500" rows="3"></textarea></label><label class="is-wide">Lien principal<input name="link_url" type="url" placeholder="https://…"></label><label class="is-wide">Live YouTube<input name="youtube_url" type="url" placeholder="https://youtube.com/watch?v=…"></label><div class="is-wide"><strong>Chaînes de diffusion</strong><div class="home-news-channel-picker" id="homeNewsChannels"></div></div></div><div class="c3k-v8-actions"><button type="button" class="secondary-btn" data-home-news-close>Annuler</button><button type="submit" class="primary-btn">Enregistrer</button></div><div class="c3k-v8-status" id="homeNewsStatus" hidden></div></form></div></section></div>`);m=$('#homeNewsEditor');$$('[data-home-news-close]',m).forEach(b=>b.onclick=()=>m.hidden=true);$('#homeNewsForm',m).addEventListener('submit',save);return m;}
  function localDate(v){if(!v)return '';const d=new Date(v);if(Number.isNaN(+d))return '';const z=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${z(d.getMonth()+1)}-${z(d.getDate())}T${z(d.getHours())}:${z(d.getMinutes())}`;}
  async function open(id=''){await load();const m=modal(),f=$('#homeNewsForm',m),r=state.rows.find(x=>String(x.id)===String(id))||{};f.reset();f.elements.id.value=r.id||'';f.elements.title.value=r.title||'';f.elements.event_at.value=localDate(r.event_at);f.elements.note.value=r.note||'';f.elements.link_url.value=r.link_url||'';f.elements.youtube_url.value=r.youtube_url||'';f.elements.active.value=r.active===false?'false':'true';f.elements.upcoming_event.checked=Boolean(r.upcoming_event);const selected=new Set(linksFor(r.id).map(x=>String(x.broadcast_channel_id)));$('#homeNewsChannels',m).innerHTML=state.channels.map(ch=>`<label><input type="checkbox" name="channels" value="${esc(ch.id)}" ${selected.has(String(ch.id))?'checked':''}><span>${esc(ch.name)}</span></label>`).join('')||'<small>Aucune chaîne enregistrée.</small>';$('#homeNewsStatus',m).hidden=true;m.hidden=false;}
  async function save(e){e.preventDefault();const c=db(),f=e.currentTarget,fd=new FormData(f),st=$('#homeNewsStatus');if(!c)return;st.hidden=false;st.className='c3k-v8-status';st.textContent='Enregistrement…';try{const id=String(fd.get('id')||''),payload={title:String(fd.get('title')||'').trim(),note:String(fd.get('note')||'').trim()||null,event_at:fd.get('event_at')?new Date(String(fd.get('event_at'))).toISOString():null,link_url:String(fd.get('link_url')||'').trim()||null,youtube_url:String(fd.get('youtube_url')||'').trim()||null,active:String(fd.get('active'))!=='false',upcoming_event:Boolean(f.elements.upcoming_event.checked),updated_at:new Date().toISOString()};let newsId=id;if(id){const x=await c.from('homepage_news').update(payload).eq('id',id);if(x.error)throw x.error;}else{payload.created_by=window.C3K_ACCOUNT_STATE?.profile?.id||null;const x=await c.from('homepage_news').insert(payload).select('id').single();if(x.error)throw x.error;newsId=x.data.id;}let x=await c.from('homepage_news_broadcast_channels').delete().eq('homepage_news_id',newsId);if(x.error)throw x.error;const channels=fd.getAll('channels').filter(Boolean);if(channels.length){x=await c.from('homepage_news_broadcast_channels').insert(channels.map((broadcast_channel_id,i)=>({homepage_news_id:newsId,broadcast_channel_id,sort_order:i})));if(x.error)throw x.error;}state.loaded=false;await load(true);await render(state.mounted);window.BLEUS3000_DATA_CACHE?.invalidateTables?.(['homepage_news','homepage_news_broadcast_channels']);st.className='c3k-v8-status is-ok';st.textContent='Actu enregistrée ✓';setTimeout(()=>mClose(),350);}catch(err){st.className='c3k-v8-status is-error';st.textContent=String(err?.message||err);}}
  const mClose=()=>{const m=$('#homeNewsEditor');if(m)m.hidden=true;};
  async function remove(id){if(!canEdit()||!confirm('Supprimer cette actu ?'))return;const x=await db().from('homepage_news').delete().eq('id',id);if(x.error)return alert(x.error.message);state.loaded=false;await load(true);render(state.mounted);}
  async function togglePin(id){if(!canEdit())return;const r=state.rows.find(x=>String(x.id)===String(id));if(!r)return;const next=!r.homepage_pinned,payload={homepage_pinned:next,homepage_pinned_at:next?new Date().toISOString():null,homepage_pinned_by:next?(window.C3K_ACCOUNT_STATE?.profile?.id||null):null,updated_at:new Date().toISOString()};const x=await db().from('homepage_news').update(payload).eq('id',id);if(x.error)return alert(x.error.message);state.loaded=false;state.page=1;await load(true);await render(state.mounted);window.BLEUS3000_DATA_CACHE?.invalidateTables?.(['homepage_news']);}
  document.addEventListener('click',e=>{if(e.target.closest('#homeNewsAddBtn'))open();const pin=e.target.closest('[data-home-news-pin]');if(pin){togglePin(pin.dataset.homeNewsPin);return;}const ed=e.target.closest('[data-home-news-edit]');if(ed)open(ed.dataset.homeNewsEdit);const del=e.target.closest('[data-home-news-delete]');if(del)remove(del.dataset.homeNewsDelete);});
  window.addEventListener('c3k:account-state',()=>{ensureAdminButton();if(state.mounted)render(state.mounted);});
  window.addEventListener('bleus:broadcasts-ready',()=>{state.loaded=false;load(true).then(()=>state.mounted&&render(state.mounted)).catch(()=>{});});
  window.BLEUS3000_HOME_NEWS={load,mount,refresh:async()=>{state.loaded=false;state.page=1;await load(true);if(state.mounted)await render(state.mounted);},open};
  setTimeout(()=>mount(),1000);
})();
