/* 3615 Bleus V1.1.68 — Rassemblements enrichis · Mise à jour exhaustive · coach unifié */
(()=>{
  'use strict';
  const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const db=()=>window.BLEUS3000_SUPABASE;
  const base=()=>window.BLEUS3000_GATHERINGS;
  const refs=()=>window.BLEUS3000_RELATIONAL_REFS;
  const acc=()=>window.C3K_ACCOUNT_STATE||{};
  const canEdit=()=>['admin','superadmin'].includes(String(acc().profile?.role||acc().role||'').toLowerCase());
  const state={loaded:false,loading:null,announced:new Map(),history:new Map(),editionLinks:new Map(),broadcastLinks:new Map(),callupMeta:new Map(),appearances:new Map(),channels:[],homePage:0,openPanels:new Set(),editor:{id:null,beforePlayers:[]}};
  const byCallup=(rows,key='callup_id')=>{const m=new Map();for(const x of rows||[]){const k=String(x[key]);if(!m.has(k))m.set(k,[]);m.get(k).push(x);}return m;};
  const fmtDate=v=>{if(!v)return '—';const d=new Date(String(v).length===10?v+'T12:00:00':v);return Number.isNaN(+d)?String(v):new Intl.DateTimeFormat('fr-FR',{day:'2-digit',month:'short',year:'numeric'}).format(d);};
  const fmtDateTime=v=>{if(!v)return '';const d=new Date(v);return Number.isNaN(+d)?String(v):new Intl.DateTimeFormat('fr-FR',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit',timeZone:'Europe/Paris'}).format(d).replace(':','h');};
  const playerName=id=>{const p=(window.BLEUS3000_PLAYERS_DB?.players||window.BLEUS3000_PLAYER_REGISTRY||[]).find(x=>String(x.id)===String(id));return p?.display_name||p?.name||base()?.rows?.flatMap(r=>r.players||[]).find(x=>String(x.player_id)===String(id))?.display_name||'Joueur';};
  const playerMap=()=>new Map((window.BLEUS3000_PLAYERS_DB?.players||window.BLEUS3000_PLAYER_REGISTRY||[]).map(p=>[String(p.id),p]));
  const metaFor=id=>state.callupMeta.get(String(id))||{};
  const listFor=id=>state.announced.get(String(id))||[];
  function eventHistoryRows(id){
    const callup=(base()?.rows||[]).find(r=>String(r.id)===String(id));if(!callup)return [];
    return (callup.events||[]).filter(e=>['withdrawal','replacement','reinforcement'].includes(e.event_type)).map(e=>{
      if(e.event_type==='replacement')return {callup_id:id,event_date:e.event_date,change_type:'replacement',player_id:e.related_player_id||null,related_player_id:e.player_id||null,previous_status:null,new_status:'replacement',note:e.description||e.title||null,source_event_id:e.id||null};
      return {callup_id:id,event_date:e.event_date,change_type:e.event_type,player_id:e.player_id||null,related_player_id:e.related_player_id||null,previous_status:null,new_status:e.event_type==='withdrawal'?'withdrawn':e.event_type,note:e.description||e.title||null,source_event_id:e.id||null};
    });
  }
  const histKey=x=>[x.change_type||'',x.event_date||'',x.player_id||'',x.related_player_id||''].join('|');
  function historyFor(id){const saved=state.history.get(String(id))||[],derived=eventHistoryRows(id),seen=new Set(saved.map(histKey)),merged=[...saved,...derived.filter(x=>!seen.has(histKey(x)))],replacementOutgoing=new Set(merged.filter(x=>x.change_type==='replacement'&&x.related_player_id).map(x=>String(x.related_player_id)));return merged.filter(x=>!(x.change_type==='withdrawal'&&x.player_id&&replacementOutgoing.has(String(x.player_id)))).sort((a,b)=>new Date(b.event_date||0)-new Date(a.event_date||0));}
  const editionsFor=id=>state.editionLinks.get(String(id))||[];
  const broadcastsFor=id=>state.broadcastLinks.get(String(id))||[];

  async function load(force=false){
    if(state.loaded&&!force)return state;
    if(state.loading)return state.loading;
    state.loading=(async()=>{
      const c=db(),rows=base()?.rows||[];if(!c||!rows.length){state.loaded=true;return state;}
      const ids=rows.map(r=>r.id),matchIds=[...new Set(rows.flatMap(r=>(r.match_links||[]).map(x=>x.match_id)).filter(Boolean))];
      const queries=[
        c.from('callup_announced_players').select('*').in('callup_id',ids).order('sort_order'),
        c.from('callup_roster_history').select('*').in('callup_id',ids).order('event_date',{ascending:false}),
        c.from('callup_competition_editions').select('*').in('callup_id',ids).order('sort_order'),
        c.from('callup_broadcast_channels').select('*').in('callup_id',ids).order('sort_order'),
        c.from('callups').select('id,fff_pdf_url,coach_id,announcement_date,status').in('id',ids),
        c.from('broadcast_channels').select('*').eq('active',true).order('name')
      ];
      const res=await Promise.all(queries);
      const errors=res.map(x=>x.error).filter(Boolean);if(errors.length)console.warn('Rassemblements enrichis',errors);
      state.announced=byCallup(res[0].data||[]);state.history=byCallup(res[1].data||[]);state.editionLinks=byCallup(res[2].data||[]);state.broadcastLinks=byCallup(res[3].data||[]);
      state.callupMeta=new Map((res[4].data||[]).map(x=>[String(x.id),x]));state.channels=res[5].data||[];
      state.appearances=new Map();
      if(matchIds.length){const {data,error}=await c.from('match_appearances').select('match_id,player_id,starter,appeared,minutes').in('match_id',matchIds);if(error)console.warn('Statuts rassemblements',error);for(const a of data||[]){const k=`${a.match_id}:${a.player_id}`;state.appearances.set(k,a);}}
      state.loaded=true;return state;
    })().finally(()=>state.loading=null);
    return state.loading;
  }

  function autoStatus(callup,row){
    const evs=callup.events||[];if(evs.some(e=>(e.event_type==='withdrawal'||e.event_type==='replacement')&&String(e.player_id||'')===String(row.player_id)))return ['✕ Forfait','is-withdrawn'];
    if(evs.some(e=>e.event_type==='replacement'&&String(e.related_player_id||'')===String(row.player_id)))return ['↔ Remplaçant','is-replacement'];
    if(evs.some(e=>e.event_type==='reinforcement'&&String(e.player_id||e.related_player_id||'')===String(row.player_id)))return ['＋ Renfort','is-reinforcement'];
    if(row.status==='withdrawn')return ['✕ Forfait','is-withdrawn'];
    if(row.status==='reserve')return ['Réserviste','is-reserve'];
    const links=callup.match_links||[];let starter=false,played=false,finished=0;
    for(const l of links){const a=state.appearances.get(`${l.match_id}:${row.player_id}`),m=refs()?.getMatch?.(l.match_id);if(m&&['FT','finished','completed'].includes(String(m.status||'').toLowerCase()))finished++;if(a?.starter)starter=true;if(a?.appeared||a?.starter||Number(a?.minutes||0)>0)played=true;}
    if(starter)return ['Titulaire','is-starter'];
    if(played)return ['Entré en jeu','is-played'];
    if(links.length&&finished===links.length)return ['Non entré','is-unused'];
    if(row.status==='replacement')return ['↔ Remplaçant','is-replacement'];
    if(row.status==='reinforcement')return ['＋ Renfort','is-reinforcement'];
    return ['Convoqué','is-called'];
  }

  function editionChip(link){
    const ed=refs()?.getCompetitionEditions?.().find(x=>String(x.id)===String(link.competition_edition_id));if(!ed)return '';
    const ent=refs()?.getCompetitionEntities?.().find(x=>String(x.id)===String(ed.competition_entity_id));
    const tag=ed.edition_tag_id?refs()?.getTag?.(ed.edition_tag_id):null;
    return tag&&window.BLEUS3000_TAGS?.chipHtml?window.BLEUS3000_TAGS.chipHtml(tag,'gathering-edition-chip'):`<span class="gathering-edition-fallback">🏆 ${esc(ent?.name||'Compétition')} · ${esc(ed.edition_label||ed.edition_year||'')}</span>`;
  }
  function coachName(callup){const id=metaFor(callup.id).coach_id||callup.coach_id;if(!id)return 'Sélectionneur à renseigner';return refs()?.people?.find(x=>String(x.id)===String(id))?.display_name||'Sélectionneur';}
  function historyHtml(callup){const h=historyFor(callup.id);if(!h.length)return '<div class="gathering-history-empty">Aucune modification enregistrée depuis l’annonce.</div>';return h.slice(0,8).map(x=>{const p=x.player_id?playerName(x.player_id):'',r=x.related_player_id?playerName(x.related_player_id):'';let text=x.note||'';if(x.change_type==='replacement')text=`${r||'Joueur'} forfait → ${p||'remplaçant'} appelé`;else if(x.change_type==='withdrawal')text=`${p} forfait${x.note?` · ${x.note}`:''}`;else if(x.change_type==='reinforcement')text=`${p} appelé en renfort${x.note?` · ${x.note}`:''}`;else if(x.change_type==='added')text=`${p} ajouté à la liste`;else if(x.change_type==='removed')text=`${p} retiré de la liste`;else if(x.change_type==='reserve')text=`${p} passe réserviste`;else if(!text)text=`${p} · ${x.previous_status||'—'} → ${x.new_status||'—'}`;return `<div class="gathering-history-row"><time>${esc(fmtDateTime(x.event_date))}</time><span>${esc(text)}</span></div>`;}).join('');}
  function panelKey(callupId,panel){return `${callupId}:${panel}`;}
  function accordionHtml(callup,panel,label,body,klass){const key=panelKey(callup.id,panel),open=state.openPanels.has(key);return `<section class="gathering-accordion ${klass}"><button type="button" class="gathering-accordion-toggle" data-gathering-panel-toggle="${esc(panel)}" data-gathering-id="${esc(callup.id)}" aria-expanded="${open?'true':'false'}"><span>${label}</span><b aria-hidden="true">${open?'⌃':'⌄'}</b></button><div class="gathering-accordion-panel" data-gathering-panel="${esc(panel)}" ${open?'':'hidden'}>${body}</div></section>`;}
  function dossierHtml(callup){const eds=editionsFor(callup.id),pdf=metaFor(callup.id).fff_pdf_url;return `<section class="gathering-dossier-meta"><span>👔 <b>${esc(coachName(callup))}</b></span><span>📅 Annonce : <b>${esc(fmtDate(callup.announcement_date))}</b></span>${pdf?`<a href="${esc(pdf)}" target="_blank" rel="noopener noreferrer">📄 PDF FFF</a>`:''}</section>${eds.length?`<div class="gathering-edition-row"><span>Convoqués par édition</span>${eds.map(editionChip).join('')}</div>`:''}`;}
  function updateFeed(callup){const items=[],seen=new Set();const push=x=>{const key=[x.type||'',x.date||'',x.player||'',x.related||'',x.text||''].join('|');if(seen.has(key))return;seen.add(key);items.push(x);};for(const h of historyFor(callup.id)){const p=h.player_id?playerName(h.player_id):'',r=h.related_player_id?playerName(h.related_player_id):'';let text=h.note||'';if(h.change_type==='replacement')text=`${r||'Joueur'} forfait → ${p||'remplaçant'} appelé`;else if(h.change_type==='withdrawal')text=`${p} forfait${h.note?` · ${h.note}`:''}`;else if(h.change_type==='reinforcement')text=`${p} appelé en renfort${h.note?` · ${h.note}`:''}`;else if(h.change_type==='added')text=`${p} ajouté à la liste`;else if(h.change_type==='removed')text=`${p} retiré de la liste`;else if(h.change_type==='reserve')text=`${p} passe réserviste`;else if(!text)text=`${p} · ${h.previous_status||'—'} → ${h.new_status||'—'}`;push({date:h.event_date,type:h.change_type,player:p,related:r,text});}for(const e of (callup.events||[])){if(['withdrawal','replacement','reinforcement'].includes(e.event_type))continue;const p=e.player_id?playerName(e.player_id):'',r=e.related_player_id?playerName(e.related_player_id):'';push({date:e.event_date,type:e.event_type,player:p,related:r,text:[e.title,e.description].filter(Boolean).join(' · ')||e.event_type});}if(callup.announcement_date&&!items.some(x=>x.type==='announcement'))push({date:`${callup.announcement_date}T12:00:00+02:00`,type:'announcement',text:'Liste annoncée'});return items.sort((a,b)=>new Date(b.date||0)-new Date(a.date||0));}
  function updatesHtml(callup){const list=updateFeed(callup);if(!list.length)return '';return `<section class="gathering-events-preview gathering-update-feed"><strong>Mise à jour</strong><div class="gathering-mini-events">${list.map(x=>{const labels={announcement:'Annonce de liste',news:'Actu',withdrawal:'Forfait',replacement:'Remplacement',reinforcement:'Renfort',conference:'Conférence',update:'Mise à jour',added:'Ajout',removed:'Retrait',reserve:'Réserve',status_change:'Statut'},icons={announcement:'📋',news:'📰',withdrawal:'✕',replacement:'↔',reinforcement:'＋',conference:'🎙️',update:'●',added:'＋',removed:'−',reserve:'◌',status_change:'●'},lab=labels[x.type]||'Mise à jour';return `<div class="gathering-mini-event"><span>${esc(icons[x.type]||'●')}</span><div><strong>${esc(lab)}</strong><em class="gathering-mini-event-note">${esc(x.text||lab)}</em><small>${esc(fmtDateTime(x.date))}</small></div></div>`;}).join('')}</div></section>`;}


  function decorateTiles(){const rows=base()?.rows||[];for(const tile of $$('.gathering-tile[data-gathering-tile]')){const id=tile.dataset.gatheringTile,callup=rows.find(r=>String(r.id)===String(id));if(!callup)continue;tile.querySelector('.gathering-dossier-extra')?.remove();const holder=document.createElement('div');holder.className='gathering-dossier-extra';holder.innerHTML=dossierHtml(callup);const summary=tile.querySelector('.gathering-summary');summary?.insertAdjacentElement('afterend',holder);const effective=base()?.effectiveRoster?.(callup)||callup.players||[],rowMap=new Map(effective.map(x=>[String(x.player_id),x]));for(const pNode of $$('.gathering-player',tile)){const idp=pNode.querySelector('[data-gathering-player]')?.dataset.gatheringPlayer,row=rowMap.get(String(idp));if(!row)continue;const [label,cls]=autoStatus(callup,row),badge=pNode.querySelector('.gathering-player-status');if(badge){badge.textContent=label;badge.className=`gathering-player-status ${cls}`;}pNode.classList.toggle('is-withdrawn',cls==='is-withdrawn');pNode.classList.toggle('is-replacement',cls==='is-replacement');}const old=tile.querySelector('.gathering-events-preview'),html=updatesHtml(callup);if(old){if(html)old.outerHTML=html;else old.remove();}else if(html){const matches=tile.querySelector('.gathering-linked-matches');if(matches)matches.insertAdjacentHTML('beforebegin',html);else tile.insertAdjacentHTML('beforeend',html);}}}

  function allRichEvents(){const rows=base()?.rows||[],out=[];for(const r of rows){const explicit=[...(r.events||[])];const has=(t,p='')=>explicit.some(e=>e.event_type===t&&(!p||String(e.player_id||'')===String(p)));if(r.announcement_date&&!has('announcement'))explicit.push({id:`ann-${r.id}`,event_type:'announcement',event_date:r.announcement_date+'T12:00:00+02:00',title:`Liste annoncée · ${r.title}`,description:`${listFor(r.id).length||r.players.length} joueur(s)`,callup_id:r.id});for(const x of r.players||[]){const when=x.updated_at||r.announcement_date;if(x.status==='withdrawn'&&!has('withdrawal',x.player_id))explicit.push({event_type:'withdrawal',event_date:when,title:`Forfait · ${playerName(x.player_id)}`,description:x.notes_short||'',player_id:x.player_id,callup_id:r.id});if(x.status==='replacement'&&!explicit.some(e=>e.event_type==='replacement'&&(String(e.player_id||'')===String(x.replacement_for||'')||String(e.related_player_id||'')===String(x.player_id||''))))explicit.push({event_type:'replacement',event_date:when,title:'Remplacement',description:x.notes_short||'',player_id:x.replacement_for,related_player_id:x.player_id,callup_id:r.id});if(x.status==='reinforcement'&&!has('reinforcement',x.player_id))explicit.push({event_type:'reinforcement',event_date:when,title:`Renfort · ${playerName(x.player_id)}`,description:x.notes_short||'',player_id:x.player_id,callup_id:r.id});}const replacementOutgoing=new Set(explicit.filter(e=>e.event_type==='replacement'&&e.player_id).map(e=>String(e.player_id)));for(const e of explicit){if(e.event_type==='withdrawal'&&e.player_id&&replacementOutgoing.has(String(e.player_id)))continue;out.push({...e,gathering:r,gathering_id:r.id});}}return out.sort((a,b)=>new Date(b.event_date||0)-new Date(a.event_date||0));}
  const evtMeta=t=>({announcement:['Annonce de liste','📋'],news:['Actu','📰'],withdrawal:['Forfait','✕'],replacement:['Remplacement','↔'],reinforcement:['Renfort','＋'],conference:['Conférence','🎙️'],update:['Mise à jour','●']}[t]||['Mise à jour','●']);
  function broadcastMarkup(callup){const links=broadcastsFor(callup.id);if(!links.length)return '';return `<div class="home-gathering-broadcasts">${links.map(l=>{const ch=state.channels.find(x=>String(x.id)===String(l.broadcast_channel_id)),label=ch?.name||'Diffusion',inner=window.BLEUS3000_BROADCASTS?.renderText?.(label)||`📺 ${esc(label)}`;return l.broadcast_url?`<a href="${esc(l.broadcast_url)}" target="_blank" rel="noopener noreferrer" title="${esc(label)}">${inner}<span>▶</span></a>`:`<span>${inner}</span>`;}).join('')}</div>`;}
  function withdrawalIdsFor(callup){const ids=new Set((callup.players||[]).filter(x=>x.status==='withdrawn').map(x=>String(x.player_id)).filter(Boolean));for(const e of callup.events||[]){if(e.event_type==='withdrawal'&&e.player_id)ids.add(String(e.player_id));if(e.event_type==='replacement'&&e.player_id)ids.add(String(e.player_id));}return [...ids];}
  function resourcesHtml(callup){const pdf=metaFor(callup.id).fff_pdf_url,withdrawn=withdrawalIdsFor(callup);if(!pdf&&!withdrawn.length&&!broadcastsFor(callup.id).length)return '';return `<section class="home-gathering-resource-card"><div class="home-gathering-resource-title"><strong>${esc(callup.title)}</strong>${pdf?`<a href="${esc(pdf)}" target="_blank" rel="noopener noreferrer" title="Convocation officielle FFF">📄 PDF FFF</a>`:''}</div>${broadcastMarkup(callup)}${withdrawn.length?`<div class="home-withdrawal-recap"><b>Forfaits (${withdrawn.length})</b>${withdrawn.map(id=>`<div class="home-replacement-recap home-withdrawal-only"><span class="out">${esc(playerName(id))}</span></div>`).join('')}</div>`:''}</section>`;}
  function richEventTile(e){const [label,icon]=evtMeta(e.event_type),p=e.player_id?playerName(e.player_id):'',rp=e.related_player_id?playerName(e.related_player_id):'';let special='';if(e.event_type==='replacement')special=`<div class="home-event-transfer"><span class="out">${esc(p||'Sortant')}</span><b aria-hidden="true">➜</b><span class="in">${esc(rp||'Entrant')}</span></div>`;else if(e.event_type==='withdrawal')special=`<div class="home-event-transfer home-withdrawal-only"><span class="out">${esc(p||e.title||'Forfait')}</span></div>`;else if(e.event_type==='reinforcement')special=`<div class="home-event-transfer"><span class="in">＋ ${esc(p||e.title||'Renfort')}</span></div>`;const displayTitle=e.event_type==='replacement'&&norm(e.title)==='forfait'?'Remplacement':(e.title||label);return `<article class="home-event-tile is-${esc(e.event_type)}" data-gathering-open="${esc(e.gathering_id)}" tabindex="0"><span class="home-event-icon">${icon}</span><div class="home-event-body"><div class="home-event-top"><span class="home-event-type">${esc(label)}</span><time class="home-event-date">${esc(fmtDateTime(e.event_date))}</time></div><strong class="home-event-title">${esc(displayTitle)}</strong>${special}${e.description?`<small class="home-event-description">${esc(e.description)}</small>`:''}${e.source_url?`<a class="home-event-source-link" href="${esc(e.source_url)}" target="_blank" rel="noopener noreferrer">▶ Voir le lien</a>`:''}<span class="home-event-gathering">📋 ${esc(e.gathering?.title||'Rassemblement France A')}</span></div></article>`;}
  function renderHome(){const host=$('#gatheringHomeEvents');if(!host)return;const all=allRichEvents(),per=5,pages=Math.max(1,Math.ceil(all.length/per));state.homePage=Math.max(0,Math.min(state.homePage,pages-1));const events=all.slice(state.homePage*per,state.homePage*per+per),latest=base()?.rows?.[0]||events[0]?.gathering;host.innerHTML=(latest?resourcesHtml(latest):'')+(events.length?events.map(richEventTile).join(''):'<div class="home-events-empty">Aucun événement de rassemblement pour le moment.</div>')+(all.length>per?`<div class="home-events-pagination"><button type="button" data-events-page="prev" ${state.homePage===0?'disabled':''}>‹</button><span>${state.homePage+1} / ${pages}</span><button type="button" data-events-page="next" ${state.homePage>=pages-1?'disabled':''}>›</button></div>`:'');$$('[data-events-page]',host).forEach(b=>b.addEventListener('click',()=>{state.homePage+=b.dataset.eventsPage==='next'?1:-1;renderHome();}));}

  function injectCompareButton(){if($('#gatheringCompareBtn'))return;const title=$('#referenceModalTitle');if(!title||title.textContent.trim()!=='Rassemblements')return;const toolbar=$('#referenceCount')?.parentElement;if(!toolbar)return;const b=document.createElement('button');b.type='button';b.id='gatheringCompareBtn';b.className='secondary-btn';b.textContent='⇄ Comparer les listes';b.addEventListener('click',openCompare);toolbar.insertBefore(b,$('#addReferenceEntry'));}
  function ensureCompareModal(){let m=$('#gatheringCompareModal');if(m)return m;document.body.insertAdjacentHTML('beforeend',`<div class="modal-backdrop" id="gatheringCompareModal" hidden><section class="modal-dialog gathering-compare-dialog"><header class="modal-head"><div><h2>Comparer deux rassemblements</h2><p>Entrants · sortants · joueurs conservés</p></div><button class="modal-close" type="button" data-gc-close>×</button></header><div class="modal-body"><div class="gathering-compare-pickers"><select id="gcA"></select><span>VS</span><select id="gcB"></select></div><div id="gcResult"></div></div></section></div>`);m=$('#gatheringCompareModal');m.querySelector('[data-gc-close]').addEventListener('click',()=>m.hidden=true);m.addEventListener('pointerdown',e=>{if(e.target===m)m.hidden=true;});$('#gcA',m).addEventListener('change',renderCompare);$('#gcB',m).addEventListener('change',renderCompare);return m;}
  function compareSet(r){const ann=listFor(r.id);return new Set((ann.length?ann:r.players||[]).filter(x=>x.status!=='withdrawn').map(x=>String(x.player_id)));}
  function names(ids){return [...ids].map(id=>`<button type="button" data-gathering-player="${esc(id)}">${esc(playerName(id))}</button>`).join('')||'<span class="gathering-compare-none">Aucun</span>';}
  function renderCompare(){const a=base()?.rows?.find(x=>String(x.id)===$('#gcA')?.value),b=base()?.rows?.find(x=>String(x.id)===$('#gcB')?.value),host=$('#gcResult');if(!a||!b||!host)return;const A=compareSet(a),B=compareSet(b),kept=new Set([...B].filter(x=>A.has(x))),incoming=new Set([...B].filter(x=>!A.has(x))),outgoing=new Set([...A].filter(x=>!B.has(x)));host.innerHTML=`<div class="gathering-compare-summary"><span><b>${kept.size}</b> conservés</span><span class="in"><b>${incoming.size}</b> entrants</span><span class="out"><b>${outgoing.size}</b> sortants</span></div><div class="gathering-compare-columns"><section><h3>🟢 Entrants</h3>${names(incoming)}</section><section><h3>🔵 Conservés</h3>${names(kept)}</section><section><h3>🔴 Sortants</h3>${names(outgoing)}</section></div>`;}
  function openCompare(){const m=ensureCompareModal(),rows=base()?.rows||[],opts=rows.map(r=>`<option value="${esc(r.id)}">${esc(r.title)} · ${esc(fmtDate(r.announcement_date))}</option>`).join('');$('#gcA',m).innerHTML=opts;$('#gcB',m).innerHTML=opts;if(rows[1])$('#gcA',m).value=rows[1].id;if(rows[0])$('#gcB',m).value=rows[0].id;m.hidden=false;renderCompare();}

  function editionOptions(selected=[]){const ids=new Set(selected.map(x=>String(x.competition_edition_id))),entities=new Map((refs()?.getCompetitionEntities?.()||[]).map(x=>[String(x.id),x]));return (refs()?.getCompetitionEditions?.()||[]).slice().sort((a,b)=>Number(b.edition_year||0)-Number(a.edition_year||0)).map(ed=>{const ent=entities.get(String(ed.competition_entity_id));return `<option value="${esc(ed.id)}" ${ids.has(String(ed.id))?'selected':''}>${esc(ent?.name||'Compétition')} · ${esc(ed.edition_label||ed.edition_year||'')}</option>`;}).join('');}
  function coachOptions(selected=''){return `<option value="">— Sélectionneur —</option>${(refs()?.people||[]).filter(x=>x.person_type==='selectionneur').sort((a,b)=>String(a.display_name).localeCompare(String(b.display_name),'fr')).map(p=>`<option value="${esc(p.id)}" ${String(p.id)===String(selected)?'selected':''}>${esc(p.display_name)}</option>`).join('')}`;}
  function channelOptions(selected=''){return `<option value="">— Chaîne —</option>${state.channels.map(c=>`<option value="${esc(c.id)}" ${String(c.id)===String(selected)?'selected':''}>${esc(c.name)}</option>`).join('')}`;}
  function addBroadcastRow(data={}){const host=$('#gatheringBroadcastRows');if(!host)return;const row=document.createElement('div');row.className='gathering-broadcast-editor-row';const local=data.scheduled_at?new Date(data.scheduled_at).toISOString().slice(0,16):'';row.innerHTML=`<select name="gb_channel">${channelOptions(data.broadcast_channel_id)}</select><select name="gb_kind"><option value="press_conference">Conférence de presse</option><option value="announcement">Annonce de liste</option><option value="training">Entraînement</option><option value="other">Autre</option></select><input name="gb_time" type="datetime-local" value="${esc(local)}"><input name="gb_url" type="url" value="${esc(data.broadcast_url||'')}" placeholder="Lien YouTube / diffusion"><button type="button" class="tile-action">×</button>`;row.querySelector('[name=gb_kind]').value=data.broadcast_kind||'press_conference';row.querySelector('button').addEventListener('click',()=>row.remove());host.appendChild(row);}
  async function enhanceEditor(){const modal=$('#gatheringEditorModal'),form=$('#gatheringEditorForm');if(!modal||modal.hidden||!form)return;await load();if(!$('#gatheringEnrichedFields',form)){const grid=$('.gathering-form-grid',form);grid?.insertAdjacentHTML('afterend',`<section class="gathering-editor-section gathering-enriched-fields" id="gatheringEnrichedFields"><header><div><strong>Dossier du rassemblement</strong><small>Sélectionneur · édition · PDF FFF · diffusions</small></div></header><div class="gathering-form-grid"><label>PDF officiel FFF<input name="enriched_pdf" type="url" placeholder="https://media.fff.fr/..."></label><label>Éditions de compétition<select name="enriched_editions" multiple size="4"></select></label></div><div class="gathering-broadcast-head"><strong>📺 Conférence / diffusions</strong><button type="button" class="secondary-btn" id="gatheringAddBroadcast">＋ Chaîne</button></div><div id="gatheringBroadcastRows"></div></section>`);$('#gatheringAddBroadcast',form)?.addEventListener('click',()=>addBroadcastRow());}
    for(const s of $$('.gathering-player-editor-row [name=status]',form)){if(![...s.options].some(o=>o.value==='reinforcement'))s.insertAdjacentHTML('beforeend','<option value="reinforcement">Renfort</option>');}
    for(const s of $$('[name=event_type]',form)){if(![...s.options].some(o=>o.value==='conference'))s.insertAdjacentHTML('beforeend','<option value="conference">Conférence</option>');}
    const id=form.elements.id.value||'',callup=base()?.rows?.find(x=>String(x.id)===String(id))||null;if(form.dataset.enrichedLoaded===String(id||'new'))return;form.dataset.enrichedLoaded=String(id||'new');state.editor.id=id||null;state.editor.beforePlayers=(base()?.effectiveRoster?.(callup)||callup?.players||[]).map(x=>({...x}));const meta=metaFor(id);if(form.elements.coach_id){form.elements.coach_id.innerHTML=coachOptions(meta.coach_id||callup?.coach_id||'');form.elements.coach_id.value=meta.coach_id||callup?.coach_id||'';}form.elements.enriched_pdf.value=meta.fff_pdf_url||'';form.elements.enriched_editions.innerHTML=editionOptions(editionsFor(id));$('#gatheringBroadcastRows',form).innerHTML='';(broadcastsFor(id)||[]).forEach(addBroadcastRow);if(!broadcastsFor(id).length)addBroadcastRow();}

  function currentEditorExtra(form){return {coach_id:form.elements.coach_id?.value||null,pdf:form.elements.enriched_pdf?.value.trim()||null,editionIds:[...(form.elements.enriched_editions?.selectedOptions||[])].map(o=>o.value),broadcasts:$$('.gathering-broadcast-editor-row',form).map((row,i)=>({broadcast_channel_id:$('[name=gb_channel]',row).value,broadcast_kind:$('[name=gb_kind]',row).value,broadcast_url:$('[name=gb_url]',row).value.trim()||null,scheduled_at:$('[name=gb_time]',row).value?new Date($('[name=gb_time]',row).value).toISOString():null,sort_order:i})).filter(x=>x.broadcast_channel_id)};}
  async function syncEventHistory(gatheringId){
    const c=db();if(!c||!gatheringId)return;
    const [{data:events,error:eventError},{data:saved,error:historyError}]=await Promise.all([
      c.from('callup_events').select('id,callup_id,event_date,event_type,title,description,player_id,related_player_id').eq('callup_id',gatheringId).in('event_type',['withdrawal','replacement','reinforcement']),
      c.from('callup_roster_history').select('change_type,event_date,player_id,related_player_id').eq('callup_id',gatheringId)
    ]);
    if(eventError)throw eventError;if(historyError)throw historyError;
    const existing=new Set((saved||[]).map(histKey)),uid=acc().profile?.id||null,rows=[];
    for(const e of events||[]){const row=e.event_type==='replacement'?{callup_id:gatheringId,event_date:e.event_date,change_type:'replacement',player_id:e.related_player_id||null,related_player_id:e.player_id||null,previous_status:null,new_status:'replacement',note:e.description||e.title||null,created_by:uid}:{callup_id:gatheringId,event_date:e.event_date,change_type:e.event_type,player_id:e.player_id||null,related_player_id:e.related_player_id||null,previous_status:null,new_status:e.event_type==='withdrawal'?'withdrawn':e.event_type,note:e.description||e.title||null,created_by:uid};const key=histKey(row);if(!existing.has(key)){existing.add(key);rows.push(row);}}
    if(rows.length){const {error}=await c.from('callup_roster_history').insert(rows);if(error)throw error;}
  }

  function historyRows(gatheringId,before,after){if(!state.editor.id)return [];const prev=new Map(before.map(x=>[String(x.player_id),x])),curr=new Map(after.map(x=>[String(x.player_id),x])),now=new Date().toISOString(),uid=acc().profile?.id||null,out=[];const replacementOutgoing=new Set(after.filter(x=>x.status==='replacement'&&x.replacement_for).map(x=>String(x.replacement_for)));
    for(const [id,p] of prev){const n=curr.get(id);if(!n){out.push({callup_id:gatheringId,event_date:now,change_type:'removed',player_id:p.player_id,previous_status:p.status,new_status:null,note:p.notes_short||null,created_by:uid});continue;}if(p.status!==n.status&&!replacementOutgoing.has(id)){const type=n.status==='withdrawn'?'withdrawal':n.status==='reserve'?'reserve':n.status==='reinforcement'?'reinforcement':'status_change';out.push({callup_id:gatheringId,event_date:now,change_type:type,player_id:n.player_id,previous_status:p.status,new_status:n.status,note:n.notes_short||null,created_by:uid});}}
    for(const [id,n] of curr){if(prev.has(id))continue;if(n.status==='replacement'&&n.replacement_for)out.push({callup_id:gatheringId,event_date:now,change_type:'replacement',player_id:n.player_id,related_player_id:n.replacement_for,previous_status:null,new_status:'replacement',note:n.notes_short||null,created_by:uid});else if(n.status==='reinforcement')out.push({callup_id:gatheringId,event_date:now,change_type:'reinforcement',player_id:n.player_id,new_status:n.status,note:n.notes_short||null,created_by:uid});else out.push({callup_id:gatheringId,event_date:now,change_type:'added',player_id:n.player_id,new_status:n.status,note:n.notes_short||null,created_by:uid});}
    return out;}
  async function afterBaseSave(gatheringId,form,dedup){const c=db();if(!c||!gatheringId)return;const extra=currentEditorExtra(form);let r=await c.from('callups').update({coach_id:extra.coach_id,fff_pdf_url:extra.pdf,updated_at:new Date().toISOString()}).eq('id',gatheringId);if(r.error)throw r.error;r=await c.from('callup_competition_editions').delete().eq('callup_id',gatheringId);if(r.error)throw r.error;if(extra.editionIds.length){r=await c.from('callup_competition_editions').insert(extra.editionIds.map((competition_edition_id,i)=>({callup_id:gatheringId,competition_edition_id,sort_order:i})));if(r.error)throw r.error;}r=await c.from('callup_broadcast_channels').delete().eq('callup_id',gatheringId);if(r.error)throw r.error;if(extra.broadcasts.length){r=await c.from('callup_broadcast_channels').insert(extra.broadcasts.map(x=>({...x,callup_id:gatheringId})));if(r.error)throw r.error;}const hist=historyRows(gatheringId,state.editor.beforePlayers,dedup);if(hist.length){r=await c.from('callup_roster_history').insert(hist);if(r.error)throw r.error;}await syncEventHistory(gatheringId);state.loaded=false;}

  async function refreshAll(){await load(true);decorateTiles();injectCompareButton();renderHome();}
  let timer=0;const observer=new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(async()=>{if($('#gatheringEditorModal')&&!$('#gatheringEditorModal').hidden)enhanceEditor().catch(console.warn);if($('#referenceModalTitle')?.textContent?.trim()==='Rassemblements'){await load();decorateTiles();injectCompareButton();}},50);});observer.observe(document.documentElement,{subtree:true,childList:true,attributes:true,attributeFilter:['hidden']});
  document.addEventListener('click',e=>{const p=e.target.closest('[data-gathering-player]');if(p&&e.target.closest('#gatheringCompareModal,.gathering-dossier-extra'))window.BLEUS3000_PLAYERS_DB?.openPlayer?.(p.dataset.gatheringPlayer);});
  window.addEventListener('bleus:gatherings-ready',()=>setTimeout(()=>refreshAll().catch(console.warn),20));
  window.addEventListener('bleus:broadcasts-ready',()=>{state.loaded=false;refreshAll().catch(()=>{});});
  window.BLEUS3000_GATHERINGS_ENRICHED={load,refresh:refreshAll,afterBaseSave,openCompare};
  setTimeout(()=>refreshAll().catch(()=>{}),900);
})();
