/* 3615 Bleus V1.1.42 — cadre de mise en avant des affiches */
(()=>{
  'use strict';
  const $=(s,p=document)=>p.querySelector(s);
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const state=()=>window.C3K_ACCOUNT_STATE||{};
  const client=()=>window.BLEUS3000_SUPABASE;
  const canEdit=()=>['editor','admin','superadmin'].includes(String(state().role||'').toLowerCase());
  let style={slug:'international',label_text:'Affiche internationale',gradient_colors:['#123b8f','#2563eb','#ffffff','#ef3340'],gradient_angle:135,border_width:2,border_radius:12,glow_color:'#2563eb',glow_strength:12};
  const colors=()=>{const a=Array.isArray(style.gradient_colors)?style.gradient_colors.filter(Boolean).slice(0,5):[];return a.length?a:['#123b8f','#2563eb','#ef3340'];};
  async function load(){const c=client();if(c){const {data,error}=await c.from('calendar_feature_styles').select('*').eq('active',true).eq('is_default',true).maybeSingle();if(!error&&data)style=data;}window.dispatchEvent(new CustomEvent('bleus:feature-style',{detail:{style}}));return style;}
  function previewCss(x=style){const cs=(x.gradient_colors||[]).filter(Boolean);return `--feature-gradient:linear-gradient(${Number(x.gradient_angle||135)}deg,${cs.join(',')});--feature-width:${Number(x.border_width||2)}px;--feature-radius:${Number(x.border_radius||12)}px;--feature-glow:${esc(x.glow_color||'#2563eb')};--feature-glow-strength:${Number(x.glow_strength||12)}px;`;}
  function open(){const body=$('#c3kV8PanelBody');if(!body)return;body.innerHTML='<div class="c3k-v8-muted">Chargement du cadre…</div>';load().then(render);}
  function render(){const body=$('#c3kV8PanelBody');if(!body)return;const cs=colors();body.innerHTML=`<section class="feature-frame-manager"><div class="feature-frame-head"><div><strong>✨ Cadre de diffusion</strong><span>Appliqué automatiquement aux équipes de France A masculine et féminine. Chaque match peut aussi forcer ou désactiver la mise en avant.</span></div></div><div class="feature-frame-preview"><article class="calendar-row is-featured" style="${previewCss({...style,gradient_colors:cs})}"><div class="calendar-date">Vendredi 9 octobre 2026 - 20H45</div><div class="calendar-fixture"><strong>🇫🇷 France</strong><span class="calendar-score">VS</span><strong>Italie 🇮🇹</strong></div></article></div>${canEdit()?`<form id="featureFrameForm" class="feature-frame-form"><label>Nom<input name="label_text" maxlength="50" value="${esc(style.label_text||'Affiche internationale')}"></label><div class="feature-frame-colors">${[0,1,2,3,4].map(i=>`<label>Couleur ${i+1}<input type="color" name="color_${i}" value="${esc(cs[i]||cs[cs.length-1]||'#2563eb')}"><input type="checkbox" name="use_${i}" ${i<cs.length?'checked':''} ${i<2?'disabled':''}></label>`).join('')}</div><div class="feature-frame-grid"><label>Angle<input name="gradient_angle" type="number" min="0" max="360" value="${Number(style.gradient_angle||135)}"></label><label>Épaisseur<input name="border_width" type="number" min="1" max="8" value="${Number(style.border_width||2)}"></label><label>Arrondi<input name="border_radius" type="number" min="0" max="32" value="${Number(style.border_radius||12)}"></label><label>Lueur<input name="glow_strength" type="number" min="0" max="40" value="${Number(style.glow_strength||12)}"></label><label>Couleur lueur<input name="glow_color" type="color" value="${esc(style.glow_color||'#2563eb')}"></label></div><div class="c3k-v8-actions"><button type="button" class="c3k-v8-secondary" id="featureFrameBack">Retour</button><button class="c3k-v8-primary" type="submit">Enregistrer</button></div><div id="featureFrameStatus" class="c3k-v8-status" hidden></div></form>`:`<div class="c3k-v8-muted">Consultation uniquement pour ce rôle.</div><div class="c3k-v8-actions"><button type="button" class="c3k-v8-secondary" id="featureFrameBack">Retour</button></div>`}</section>`;
    $('#featureFrameBack')?.addEventListener('click',()=>$('#c3kV8AccountBtn')?.click());
    $('#featureFrameForm')?.addEventListener('input',previewFromForm);$('#featureFrameForm')?.addEventListener('submit',save);
  }
  function dataFromForm(){const f=$('#featureFrameForm'),fd=new FormData(f),cs=[];for(let i=0;i<5;i++)if(i<2||fd.get(`use_${i}`))cs.push(String(fd.get(`color_${i}`)||'#2563eb'));return {label_text:String(fd.get('label_text')||'Affiche internationale').trim(),gradient_colors:cs.slice(0,5),gradient_angle:Number(fd.get('gradient_angle')||135),border_width:Number(fd.get('border_width')||2),border_radius:Number(fd.get('border_radius')||12),glow_strength:Number(fd.get('glow_strength')||12),glow_color:String(fd.get('glow_color')||'#2563eb')};}
  function previewFromForm(){const x={...style,...dataFromForm()},p=document.querySelector('.feature-frame-preview .calendar-row');if(p)p.style.cssText=previewCss(x);}
  async function save(e){e.preventDefault();const c=client(),st=$('#featureFrameStatus');if(!c)return;const payload={...dataFromForm(),updated_by:state().profile?.id||null,updated_at:new Date().toISOString()};st.hidden=false;st.textContent='Enregistrement…';const {data,error}=await c.from('calendar_feature_styles').update(payload).eq('slug','international').select('*').single();if(error){st.className='c3k-v8-status is-error';st.textContent=error.message;return;}style=data;st.className='c3k-v8-status is-ok';st.textContent='Cadre enregistré ✓';window.dispatchEvent(new CustomEvent('bleus:feature-style',{detail:{style}}));window.BLEUS3000_CALENDAR?.setFeatureStyle?.(style);setTimeout(()=>{if(st.isConnected)st.hidden=true;},1200);}
  window.BLEUS3000_FEATURE_FRAMES={open,load,getStyle:()=>({...style}),previewCss};
  window.addEventListener('bleus:supabase-ready',()=>load());
})();
