/* 3615 Bleus V1.1.61.44 — lieux, navigation confrontations et médias de match */
(()=>{
  'use strict';
  const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const db=()=>window.BLEUS3000_SUPABASE, refs=()=>window.BLEUS3000_RELATIONAL_REFS;
  const canEdit=()=>['admin','superadmin'].includes(String(window.C3K_ACCOUNT_STATE?.profile?.role||window.C3K_ACCOUNT_STATE?.role||'').toLowerCase());
  let mediaLoaded=false,mediaLoading=null,media=[];
  const byMatch=id=>media.filter(x=>String(x.match_id)===String(id)).sort((a,b)=>(a.sort_order||0)-(b.sort_order||0)||String(a.created_at||'').localeCompare(String(b.created_at||'')));
  const photoUrl=x=>{if(x?.image_url)return x.image_url;if(x?.image_path&&db())try{return db().storage.from('reference-photos').getPublicUrl(x.image_path).data.publicUrl||'';}catch{}return '';};
  const dateVal=m=>new Date(m?.match_date||0).getTime()||0;
  function youtubeId(url){const s=String(url||'').trim();const m=s.match(/(?:youtu\.be\/|youtube(?:-nocookie)?\.com\/(?:watch\?v=|embed\/|shorts\/))([A-Za-z0-9_-]{6,})/i);return m?.[1]||'';}
  async function loadMedia(force=false){if(mediaLoaded&&!force)return media;if(mediaLoading)return mediaLoading;const c=db();if(!c)return[];mediaLoading=(async()=>{const {data,error}=await c.from('match_media_assets').select('*').order('sort_order').order('created_at');if(error&&String(error.code)!=='42P01')throw error;media=data||[];mediaLoaded=true;return media;})().finally(()=>mediaLoading=null);return mediaLoading;}
  function openPlaceSearch(q){if(!q)return;window.BLEUS3000_APP?.openReferences?.('lieux');setTimeout(()=>{const i=$('#referenceSearch');if(i){i.value=q;i.dispatchEvent(new Event('input',{bubbles:true}));i.focus();}},100);}
  function confrontationState(m){const all=(refs()?.matches||[]).filter(x=>x.opponent_id&&String(x.opponent_id)===String(m.opponent_id)).sort((a,b)=>dateVal(a)-dateVal(b));const idx=all.findIndex(x=>String(x.id)===String(m.id));if(idx<0)return {prev:null,next:null,warning:'Match absent de la série de confrontation'};const prev=all[idx-1]||null,next=all[idx+1]||null,day=String(m.match_date||'').slice(0,10),dupe=all.some(x=>String(x.id)!==String(m.id)&&String(x.match_date||'').slice(0,10)===day);let warning='';if(dupe)warning='Deux matchs contre cet adversaire partagent la même date';else if(prev&&dateVal(prev)>=dateVal(m))warning='Ordre chronologique précédent incohérent';else if(next&&dateVal(next)<=dateVal(m))warning='Ordre chronologique suivant incohérent';return {prev,next,warning,count:all.length};}
  function mediaHtml(matchId){const rows=byMatch(matchId);if(!rows.length)return '';const papers=rows.filter(x=>x.asset_type==='newspaper_front'),tickets=rows.filter(x=>x.asset_type==='ticket'),videos=rows.filter(x=>x.asset_type==='youtube'&&youtubeId(x.url));const imageCard=(x,label)=>{const u=photoUrl(x);return u?`<a class="match-media-image" href="${esc(x.url||u)}" target="_blank" rel="noopener noreferrer"><img src="${esc(u)}" alt="${esc(x.title||label)}" loading="lazy"><span>${esc(x.title||label)}</span></a>`:'';};return `<details class="match-media-panel"><summary>🗞️ Médias du match · ${rows.length}</summary><div class="match-media-content">${papers.length?`<section><h4>Unes de journaux</h4><div class="match-media-gallery">${papers.map(x=>imageCard(x,'Une de journal')).join('')}</div></section>`:''}${tickets.length?`<section><h4>Billets historiques</h4><div class="match-media-gallery">${tickets.map(x=>imageCard(x,'Billet du match')).join('')}</div></section>`:''}${videos.length?`<section><h4>Vidéos</h4><div class="match-video-grid">${videos.map(x=>`<div><iframe loading="lazy" src="https://www.youtube-nocookie.com/embed/${esc(youtubeId(x.url))}" title="${esc(x.title||'Vidéo du match')}" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>${x.title?`<strong>${esc(x.title)}</strong>`:''}</div>`).join('')}</div></section>`:''}</div></details>`;}
  function decorateCard(card){const id=card.dataset.matchId;if(!id||card.dataset.v16144Decorated==='1')return;const m=refs()?.getMatch?.(id);if(!m)return;card.dataset.v16144Decorated='1';const facts=$('.rel-facts',card),place=m.place||null;if(facts&&place){const nav=document.createElement('div');nav.className='match-place-links';nav.innerHTML=`${place.name?`<button type="button" data-match-place-search="${esc(place.name)}">🏟 ${esc(place.name)}</button>`:''}${place.city?`<button type="button" data-match-place-search="${esc(place.city)}">📍 ${esc(place.city)}</button>`:''}`;facts.appendChild(nav);}
    const c=confrontationState(m),bottom=$('.rel-match-bottom',card);if(bottom){const nav=document.createElement('div');nav.className='match-confrontation-nav';nav.innerHTML=`<button type="button" data-confrontation-match="${esc(c.prev?.id||'')}" ${c.prev?'':'disabled'} title="Confrontation précédente">← Précédente</button><span title="${esc(c.warning||'Ordre chronologique vérifié')}">${c.warning?'⚠':'✓'} ${c.count||1} confrontation${(c.count||1)>1?'s':''}</span><button type="button" data-confrontation-match="${esc(c.next?.id||'')}" ${c.next?'':'disabled'} title="Confrontation suivante">Suivante →</button>`;bottom.insertAdjacentElement('beforebegin',nav);}
    const mh=mediaHtml(id);if(mh)bottom?.insertAdjacentHTML('beforebegin',mh);if(canEdit()&&bottom&&!$('[data-match-media-edit]',card)){$('.rel-match-actions',bottom)?.insertAdjacentHTML('beforeend',`<button type="button" class="rel-match-media-btn" data-match-media-edit="${esc(id)}">＋ Médias</button>`);}
  }
  async function decorateAll(){await loadMedia();$$('.rel-match-tile[data-match-id]').forEach(decorateCard);}
  async function uploadImage(matchId,file,type){if(!file)return null;if(file.size>5*1024*1024)throw new Error('L’image dépasse 5 Mo.');const ext=(String(file.name||'').split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,''),safe=['png','jpg','jpeg','webp'].includes(ext)?ext:'jpg',path=`match-media/${matchId}/${type}-${Date.now()}-${crypto.randomUUID()}.${safe}`;const {error}=await db().storage.from('reference-photos').upload(path,file,{contentType:file.type||undefined,upsert:false});if(error)throw error;return path;}
  function ensureModal(){let m=$('#matchMediaEditor');if(m)return m;document.body.insertAdjacentHTML('beforeend',`<div class="modal-backdrop" id="matchMediaEditor" hidden><section class="modal-dialog match-media-dialog" role="dialog" aria-modal="true"><header class="modal-head"><div><h2>Médias du match</h2><p>Unes de journaux · billets · vidéos YouTube</p></div><button type="button" class="modal-close" data-match-media-close>×</button></header><div class="modal-body"><div id="matchMediaExisting"></div><form id="matchMediaForm" class="match-media-form"><input type="hidden" name="match_id"><label>Type<select name="asset_type"><option value="newspaper_front">Une de journal</option><option value="ticket">Billet historique</option><option value="youtube">Vidéo YouTube</option></select></label><label>Titre<input name="title" maxlength="180" placeholder="Titre / description"></label><label>URL / YouTube<input name="url" type="url" placeholder="https://…"></label><label>Image externe<input name="image_url" type="url" placeholder="https://…"></label><label>Ou importer l’image<input name="image_file" type="file" accept="image/png,image/jpeg,image/webp"></label><div class="match-media-actions"><button type="button" class="secondary-btn" data-match-media-close>Fermer</button><button type="submit" class="primary-btn">Ajouter</button></div><div class="c3k-v8-status" id="matchMediaStatus" hidden></div></form></div></section></div>`);m=$('#matchMediaEditor');$$('[data-match-media-close]',m).forEach(b=>b.onclick=()=>m.hidden=true);$('#matchMediaForm',m).addEventListener('submit',saveMedia);return m;}
  function renderExisting(matchId){const host=$('#matchMediaExisting'),rows=byMatch(matchId);host.innerHTML=rows.length?`<div class="match-media-existing">${rows.map(x=>`<div><span>${x.asset_type==='youtube'?'▶':x.asset_type==='ticket'?'🎟️':'🗞️'}</span><strong>${esc(x.title||({youtube:'YouTube',ticket:'Billet historique',newspaper_front:'Une de journal'}[x.asset_type]||'Média'))}</strong><button type="button" data-delete-match-media="${esc(x.id)}">×</button></div>`).join('')}</div>`:'<div class="match-media-empty">Aucun média associé.</div>';$$('[data-delete-match-media]',host).forEach(b=>b.onclick=async()=>{if(!confirm('Supprimer ce média ?'))return;const row=media.find(x=>String(x.id)===String(b.dataset.deleteMatchMedia));const {error}=await db().from('match_media_assets').delete().eq('id',b.dataset.deleteMatchMedia);if(error)return alert(error.message);if(row?.image_path)db().storage.from('reference-photos').remove([row.image_path]).catch(()=>{});mediaLoaded=false;await loadMedia(true);renderExisting(matchId);refreshCards();});}
  async function openMedia(matchId){await loadMedia();const m=ensureModal();$('#matchMediaForm',m).reset();$('#matchMediaForm [name=match_id]',m).value=matchId;$('#matchMediaStatus',m).hidden=true;renderExisting(matchId);m.hidden=false;}
  async function saveMedia(e){e.preventDefault();const f=e.currentTarget,fd=new FormData(f),matchId=String(fd.get('match_id')||''),type=String(fd.get('asset_type')||''),st=$('#matchMediaStatus');if(!matchId)return;st.hidden=false;st.className='c3k-v8-status';st.textContent='Ajout…';try{const file=f.elements.image_file?.files?.[0]||null,imagePath=await uploadImage(matchId,file,type),url=String(fd.get('url')||'').trim()||null,imageUrl=String(fd.get('image_url')||'').trim()||null;if(type==='youtube'&&!youtubeId(url))throw new Error('Lien YouTube invalide.');if(type!=='youtube'&&!imagePath&&!imageUrl)throw new Error('Ajoute une image importée ou une URL d’image.');const payload={match_id:matchId,asset_type:type,title:String(fd.get('title')||'').trim()||null,url,image_url:imageUrl,image_path:imagePath,created_by:window.C3K_ACCOUNT_STATE?.profile?.id||null};const {error}=await db().from('match_media_assets').insert(payload);if(error)throw error;mediaLoaded=false;await loadMedia(true);renderExisting(matchId);f.reset();f.elements.match_id.value=matchId;st.className='c3k-v8-status is-ok';st.textContent='Média ajouté ✓';refreshCards();}catch(err){st.className='c3k-v8-status is-error';st.textContent=String(err?.message||err);}}
  function refreshCards(){$$('.rel-match-tile[data-match-id]').forEach(c=>{c.dataset.v16144Decorated='';$('.match-place-links',c)?.remove();$('.match-confrontation-nav',c)?.remove();$('.match-media-panel',c)?.remove();$('[data-match-media-edit]',c)?.remove();decorateCard(c);});}
  document.addEventListener('click',e=>{const p=e.target.closest('[data-match-place-search]');if(p){e.stopPropagation();openPlaceSearch(p.dataset.matchPlaceSearch);return;}const c=e.target.closest('[data-confrontation-match]');if(c&&c.dataset.confrontationMatch){e.stopPropagation();refs()?.openMatch?.(c.dataset.confrontationMatch);return;}const m=e.target.closest('[data-match-media-edit]');if(m){e.stopPropagation();openMedia(m.dataset.matchMediaEdit);}});
  let timer=0;const obs=new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(decorateAll,50);});obs.observe(document.documentElement,{subtree:true,childList:true});window.addEventListener('bleus:supabase-ready',()=>{mediaLoaded=false;setTimeout(decorateAll,100)});setTimeout(decorateAll,900);
})();
