/* 3615 Bleus V1.1.89 — scoreline pays avec surlignage multi-couleurs */
(()=>{
  'use strict';
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const norm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
  const fallback={fr:'#153f9e',tr:'#e11f2a',be:'#171717',it:'#148447',de:'#1b1b1b',es:'#d11f2e',pt:'#b5122b',nl:'#e36b22',br:'#178447',ar:'#69b7e7',hr:'#d61f2c',ma:'#c1272d',ua:'#1e68b5',ch:'#d52b1e',dk:'#c8102e',at:'#d81e33',pl:'#dc143c',rs:'#c6363c',cz:'#174b8d',ro:'#154da3',hu:'#c8102e',se:'#1769aa',no:'#ba0c2f',ie:'#169b62',gr:'#0d5eaf',us:'#b22234',ca:'#d80621'};
  const validColor=(value,fb)=>{const v=String(value||'').trim();return /^#(?:[0-9a-f]{3}|[0-9a-f]{6}|[0-9a-f]{8})$/i.test(v)||/^(?:rgb|hsl)a?\(/i.test(v)?v:fb;};
  const countryName=v=>window.BLEUS3000_FLAGS?.countryName?.(v)||String(v||'');
  function fallbackColor(team){const code=String(window.BLEUS3000_FLAGS?.codeFor?.(team)||'').toLowerCase();if(fallback[code])return fallback[code];return norm(team)==='france'?'#153f9e':'#315f9a';}
  function highlight(team){const fb=fallbackColor(team),o=window.BLEUS3000_COUNTRY_COLORS?.get?.(team)||null;let colors=Array.isArray(o?.highlight_colors)?o.highlight_colors.map(x=>validColor(x,fb)).filter(Boolean).slice(0,5):[];if(!colors.length)colors=[validColor(o?.primary_color,fb),validColor(o?.secondary_color||o?.primary_color,fb)];while(colors.length<2)colors.push(colors[0]||fb);const type=o?.highlight_gradient_type==='radial'?'radial':'linear',angle=Math.max(0,Math.min(360,Number(o?.gradient_angle??90)||90)),opacity=Math.max(.05,Math.min(.95,Number(o?.highlight_opacity??.28)||.28)),height=Math.max(35,Math.min(120,Number(o?.highlight_height??82)||82));const stops=colors.map((c,i)=>`${c} ${Math.round(i*100/Math.max(1,colors.length-1))}%`).join(',');const gradient=type==='radial'?`radial-gradient(ellipse at center,${stops})`:`linear-gradient(${angle}deg,${stops})`;return {colors,gradient,opacity,height};}
  function highlightStyle(c){return `--b3k-score-mark-gradient:${c.gradient};--b3k-score-mark-opacity:${c.opacity};--b3k-score-mark-height:${c.height}%`;}
  function flag(team){return window.BLEUS3000_FLAGS?.img?.(team,'b3k-scoreline-flag-img')||'<span class="b3k-scoreline-flag-img is-missing">◌</span>';}
  function team(teamName,side){const colors=highlight(teamName),name=countryName(teamName);return `<span class="b3k-scoreline-team is-${side}" data-scoreline-team="${esc(teamName)}" style="${esc(highlightStyle(colors))}">${side==='left'?`<span class="b3k-scoreline-flag">${flag(teamName)}</span>`:''}<strong class="b3k-scoreline-name">${esc(name)}</strong>${side==='right'?`<span class="b3k-scoreline-flag">${flag(teamName)}</span>`:''}</span>`;}
  function render(left,right,center,opts={}){const label=String(center??'VS').trim()||'VS',compact=Boolean(opts.compact),outcome=String(opts.outcome||''),matchId=String(opts.matchId||''),classes=['b3k-scoreline',compact?'is-compact':'',/^VS$/i.test(label)?'is-vs':'',outcome?`is-${outcome}`:''].filter(Boolean).join(' ');return `<div class="${classes}"${matchId?` data-match-id="${esc(matchId)}"`:''} aria-label="${esc(countryName(left))} ${esc(label)} ${esc(countryName(right))}">${team(left,'left')}<span class="b3k-scoreline-center">${esc(label)}</span>${team(right,'right')}</div>`;}
  function hydrate(root=document){root.querySelectorAll?.('[data-scoreline-team]').forEach(el=>{const c=highlight(el.dataset.scorelineTeam||'');el.style.setProperty('--b3k-score-mark-gradient',c.gradient);el.style.setProperty('--b3k-score-mark-opacity',String(c.opacity));el.style.setProperty('--b3k-score-mark-height',`${c.height}%`);});}
  window.BLEUS3000_SCORELINE={render,highlight,hydrate};
  window.addEventListener('bleus:country-colors-ready',()=>hydrate());
  window.addEventListener('bleus:country-colors-changed',()=>hydrate());
})();
